### ISSUE TITLE
FullNameRandomzier vs NameRandomizer

### ISSUE THREAD

**Issue by PascalSchumacher** [benas/random-beans#110]
Both generate the same data, because in java-faker `fullName()` is just an an alias for `name()`

```java
   public String fullName() {
        return name();
    }
```
I think we should remove one of the randomizers.

What do you think?

**Comment by benas** [comment]
yes we can keep FullNameRandomizer and remove NameRandomizer.
This way we have: FirstName, LastName and FullName randomizers.
