### ISSUE TITLE
First Collection without seed empty

### ISSUE THREAD

**Issue by punkratz312** [benas/random-beans#113]
My Class has 4 fields:

        String string;

        Collection<String> strings;

        Collection<String> strings2;

        Collection<String> strings3;

without seed the first collection "strings" is empty. 

I´ve debugged the code a little. It was quite confusing that ArrayPopulator.getRandomPrimitiveArray (59) randomSize is 0 if its the first collection (enhancedRandom.nextInt() returns 0). Hopefully thats a useful hint ^^.

![screen shot 2016-04-14 at 15 11 46](https://cloud.githubusercontent.com/assets/8830888/14529673/f6ed7fa2-0255-11e6-8158-2e39ee13d7df.png)
![screen shot 2016-04-14 at 15 24 08](https://cloud.githubusercontent.com/assets/8830888/14529674/f6f21404-0255-11e6-9bc7-3e897c3a09f0.png)

**Comment by punkratz312** [comment]
But that not even my original problem, I have issues with the crazy chines chars. I´am serializing the Bean and get some issues. Why aren´t the strings of the collection similar to the simple field String?

**Comment by PascalSchumacher** [comment]
>I´ve debugged the code a little. It was quite confusing that ArrayPopulator.getRandomPrimitiveArray (59) randomSize is 0 if its the first collection (enhancedRandom.nextInt() returns 0). 

I just took a look at the code. If you do not pass a seed random-beans always uses the same default seed: 1234567890L. For this reason the generated values are not really random. In each execution the same sequence of numbers will be generated. I think it would be better if random-beans was changed to use a random seed.

>I have issues with the crazy chines chars.

Looks like the strings also contain non-printable/control characters. I guess random-beans should stick to printable characters (maybe it's a good idea to make this configurable?).

**Comment by punkratz312** [comment]
Nice approach, fixed the problem: (First 2.0.0, Second 3.0.0-SNAPSHOT)
![screen shot 2016-04-15 at 11 15 01](https://cloud.githubusercontent.com/assets/8830888/14557121/f178a276-02fb-11e6-9ff3-58a951915563.png)
![screen shot 2016-04-15 at 11 18 50](https://cloud.githubusercontent.com/assets/8830888/14557122/f18f322a-02fb-11e6-9ec2-1805c187c1e8.png)

**Comment by punkratz312** [comment]
Would it be possible to change, or at lease make it configureable to change these chinese characters.

![screen shot 2016-04-15 at 11 21 19](https://cloud.githubusercontent.com/assets/8830888/14557177/462d2e18-02fc-11e6-8835-341902fa5715.png)

**Comment by benas** [comment]
Hi @punkratz312 

Thank you for raising out this issue and for taking time to debug the code!

> I´ve debugged the code a little. It was quite confusing that ArrayPopulator.getRandomPrimitiveArray (59) randomSize is 0 if its the first collection (enhancedRandom.nextInt() returns 0).

@PascalSchumacher has kindly fixed this problem with a random seed. Thank you Pascal

> I have issues with the crazy chines chars.


In regards to this point, the problem is that random-beans detects that it should generate random strings in the `Collection<String> strings` field, but instead of using the `StringRandomizer`, it is actually introspecting the `String` class and trying to populate its fields (int hash, char[] value, etc).
Here is were the problem occurs, when trying to populate the field `char[] value` of the `String` class.

I'll fix this asap and keep you informed.

> Would it be possible to change, or at lease make it configureable to change these chinese characters.

From a library design point of view, when the user asks for a random char, this is completely valid.
Our Chinese friends will be happy :smile:  How do you suggest to make this configurable? for example, should we specify at construction time which character set should random beans generate random chars from? May be another idea? I would like to hear your thoughts.

Kind regards
Mahmoud

**Comment by punkratz312** [comment]
@benas I agree, a random char is completely valid. But the encoding issue is definitely a risk.
Maybe the EnhancedRandomBuilder would be a point where the configuration could be placed. I write myselfe in every project I use your nice tool a Util class like this:

<code>

    @UtilityClass
    public final class TestUtil {
    public final static <T> T randomBean(Class<T> clazz) throws JsonProcessingException {

        return randomBean(clazz, "");
    }

    public final static <T> T randomBean(Class<T> clazz, String... excludedFields) throws JsonProcessingException {

        return aNewEnhancedRandomBuilder().build().nextObject(clazz, excludedFields);
    }

    public final static <T> Collection<T> randomBeans(Class<T> clazz, int amount) throws JsonProcessingException {

        return aNewEnhancedRandomBuilder().build().nextObjects(clazz, amount);
    }
}
</code>

I´m not sure whats the purpos of forcing the user to create a builder and stuff like that.

**Comment by benas** [comment]
> But the encoding issue is definitely a risk.

Not sure this is an encoding issue. Here is the code snippet of how the library generate random char:

```
char c = (char) EnhancedRandomBuilder.aNewEnhancedRandomBuilder().build().nextInt();
```

This generates random chars from a very large range, I'll limit it to only alphabet characters.

> I´m not sure whats the purpos of forcing the user to create a builder and stuff like that.

The purpose it to be able to set all parameters at construction time. (seed, classpath scanning for concrete types, and other parameters.)

A syntax like `randomBean(MyType.class)` is [being analyzed](https://github.com/benas/random-beans/issues/29) and will be [integrated asap](https://github.com/benas/random-beans/pull/98). keep tuned :wink:

**Comment by punkratz312** [comment]
@benas thanks for the detailed answer.

**Comment by benas** [comment]
Hi @punkratz312 ,

I've just pushed two fixes to address your problem:
* Random chars are now limited to alphabic letters
* Generic types in collections will be randomized using registered randomizers

Your test case should be fine now:

![untitled](https://cloud.githubusercontent.com/assets/1210553/14563962/aed1ac14-0324-11e6-8033-06d022271674.png)

Please let me know if it's ok for you.

Kind regards
Mahmoud

**Comment by punkratz312** [comment]
Nice, thanks a lot - works perfectly well.

![audience-applause](https://cloud.githubusercontent.com/assets/8830888/14564401/b2c16fd8-0326-11e6-8731-2fbe9043ce47.jpg)

**Comment by benas** [comment]
Thank you!

Glad that helped.

**Comment by punkratz312** [comment]
I haven't found the 3.0.0-SNAPSHOT in mvn central or something, I guess i´ll have to wait for 3.0.0?

**Comment by benas** [comment]
I'll publish it tonight.
I'm behind a nasty proxy :rage: sorry for that

**Comment by punkratz312** [comment]
Wow great, thanks a lot, again ^^ - what a service.

**Comment by benas** [comment]
Hi,

All artifacts have been deployed to maven central.

Regards
Mahmoud

**Comment by punkratz312** [comment]
Thanks 👍 

![screen shot 2016-04-18 at 10 19 39](https://cloud.githubusercontent.com/assets/8830888/14597791/3b43653a-054f-11e6-9aaf-ef9f39471a95.png)
