### ISSUE TITLE
Is bean validation really working? What am i doing wrong?

### ISSUE THREAD

**Issue by jstreicheryatta** [benas/random-beans#147]
So i read that the random generation would adhere to bean validation annotations, but for me it does in fact not.

A simple example testcase:

import io.github.benas.randombeans.EnhancedRandomBuilder;
import io.github.benas.randombeans.api.EnhancedRandom;

import org.junit.Test;

public class ToTestRandom {
	
	@Test
	public void testMe() {
		EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder().build();
		MyTest test = enhancedRandom.nextObject(MyTest.class);
		
		System.out.println(test.getTest());
	}
}

import javax.persistence.Entity;
import javax.validation.constraints.Size;

@Entity
public class MyTest {
	
	@Size(max = 5)
	private String test;
	
	public String getTest() {
		return test;
	}
	
	public void setTest(String test) {
		this.test = test;
	}
}

Will still give me test Strings much larger than 5 characters. Am i doing something wrong?

**Comment by benas** [comment]
Hi,

There is nothing wrong with your code. This issue has been already fixed in version 3.1.0-SNAPSHOT. Can you give it a try with this version? Please add the snapshot repository as detailed [here](https://github.com/benas/random-beans/wiki/Getting-Started#maven-usage).

BTW, v3.1 will be released by the end of this week.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi,

Version 3.1.0 has been released. Your test should pass with this version.
Can you please test with the new version?

Many thanks upfront.
Kind regards
Mahmoud

**Comment by jstreicheryatta** [comment]
I loaded 3.1.0 via Maven, it still creates a too long attribute test.

**Comment by benas** [comment]
Have you added the `random-beans-validation` module to your project?

Working fine with version 3.1.0 here: https://gist.github.com/benas/cace0f861c70b2b16361d650799a00cb

**Comment by jstreicheryatta** [comment]
No, i indeed only added random-beans. I will add the other module and try again.

**Comment by jstreicheryatta** [comment]
It works fine - sorry, i just didn't see that the dependency in the validation wiki page was different from the one provided on the code page.
