### ISSUE TITLE
Allow null values to be created

### ISSUE THREAD

**Issue by kermit-the-frog** [benas/random-beans#158]
Hi,

is there a way to configure random beans to generate either null or a random value (without creating a randomizer for every class)?

Kind regards
kermit-the-frog

**Comment by benas** [comment]
Hi,

> generate either null or a random value

Based on which criteria?

Kind regards
Mahmoud

**Comment by kermit-the-frog** [comment]
Hi,

> Based on which criteria?

Ok here is my specific use case. There is are some classes `Foo`, `Bar`, ...

```
class Foo {
    @XmlAttribute(required = true)
    String str1
    @XmlAttribute(required = false)
    String str2;
    String str3;
...
}

class Bar {
    @XmlElement(required = true)
    Foo foo1;
    @XmlElement(required = false)
    Foo foo2;
    @XmlAttribute(required = true)
    String str1
    Foo foo3;
...
}
```

`sfsdf sdf  sdf`

Id' like `Foo,str2` and `Foo.str3` to be either null or an instance of `String` based on random. `Bar.foo2` and `Bar.foo3` should be either `null` or an instance of `Foo`. It would be great if I can configure the probability (percentage) of null values

Kind regards,
Martin

**Comment by benas** [comment]
I see. You can use a custom registry to implement your specific case. For example:

```java
@Priority(1)
public class XmlAnnotationRegistry implements RandomizerRegistry {

    @Override
    public Randomizer<?> getRandomizer(Field field) {
            if (field.isAnnotationPresent(XmlAttribute.class)) { // handle @XmlElement too
                // return the right randomizer based on your specific criteria
                return new OptionalRandomizer(delegate, percent); // or return the NullRandomizer
            }
        return null;
    }
}
```

then add your registry as described [here](https://github.com/benas/random-beans/wiki/Grouping-Randomizers#2-or-explicitly-using-the-enhancedrandombuilder-api).

> It would be great if I can configure the probability (percentage) of null values

I think you can use the [](https://github.com/benas/random-beans/blob/master/random-beans/src/main/java/io/github/benas/randombeans/randomizers/misc/OptionalRandomizer.java) for that (in combination with a custom registry as in the previous example).

Please let me know if this helps.

Kind regards
Mahmoud

**Comment by kermit-the-frog** [comment]
Sounds good, but how do I get `delegate`? That should be the "normal" randomizer for that field.

**Comment by benas** [comment]
You need to provide the delegate. But may be the `OptionalRandomizer` is not what you need. It was just a suggestion to test.

To return the "normal" randomizer, just return null.

In your case, I think you can simply do this:

```java
@Priority(1)
public class XmlAnnotationRegistry implements RandomizerRegistry {

    @Override
    public Randomizer<?> getRandomizer(Field field) {
            if (field.isAnnotationPresent(XmlAttribute.class)) { // handle @XmlElement too
                if (shouldReturnNull()) { // implement the probability here
                    return new NullRandomizer(); // the field will be set to null
                }
            }
        return null; // this will use the "normal" randomizer, and the field will be randomized
    }
}
```

**Comment by kermit-the-frog** [comment]
Sounds perfect. I'll test it

**Comment by benas** [comment]
Please let me know if that helped. I'm curious!

**Comment by kermit-the-frog** [comment]
It works perfectly. Thanks a lot
