### ISSUE TITLE
FieldDefinition should be more flexible

### ISSUE THREAD

**Issue by benas** [benas/random-beans#160]
As of version 3.1, `FieldDefinition` must be specified with 3 attributes: field name, type and declaring class. As [discussed](https://github.com/benas/random-beans/issues/82#issuecomment-190282286) in #82 , this has some shortcomings:

* It is not possible to exclude a field only by name
* It is not possible to exclude a field annotated with a given annotation (issue #156 )

`FieldDefinition` should allow to define all characteristics of a field and random beans should combine them as needed. The idea is to be able to define fields:

* by name
* by type
* by declaring class
* by present annotations
* Any combination of the above

All combinations should be usable both for field exclusion and for randomizer registration

**Comment by PascalSchumacher** [comment]
great feature :+1:

**Comment by benas** [comment]
Thank you Pascal!

**Comment by benas** [comment]
Well,  [removing this check](https://github.com/benas/random-beans/commit/a10a4e09a2b3d05356e7185f74ae0f9c91a6ccdb#diff-1d684494efc57780c14990e33f11e1c0L91) to add some flexibility to the `FieldDefinition` is good for field exclusion. But it can be inconsistent for custom randomizer registration. Look at this example, I want to use the `ConstantRandomizer` for all fields named `name`:

```java
    @Test
    public void ambigousFieldDefinition() {
        enhancedRandom = aNewEnhancedRandomBuilder()
                .randomize(field().named("name").get(), new ConstantRandomizer<>("name"))
                .build();

        Person person = enhancedRandom.nextObject(Person.class);

        assertThat(person.getName()).isEqualTo("name");
        assertThat(person.getAddress().getStreet().getName()).isEqualTo("name");
    }
```

What if there is a field named `name` in the object graph which is not of type `String` ? ..

Another example, this is valid code:

```java
    @Test
    public void ambigousFieldDefinition() {
        enhancedRandom = aNewEnhancedRandomBuilder()
                .randomize(field().inClass(Person.class).get(), new ConstantRandomizer<>("name"))
                .build();

        Person person = enhancedRandom.nextObject(Person.class);

        assertThat(person.getName()).isEqualTo("name");
        assertThat(person.getAddress().getStreet().getName()).isEqualTo("name");
    }
```

All fields declared in `Person` class would be randomized with the  `ConstantRandomizer` regardless their type, this makes no sense.

> All combinations should be usable both for field exclusion and for randomizer registration

So the new flexibility added to field exclusion leads to possible confusing randomizers setup. Arrrrrgh :rage1: There are some adhoc solutions for sure.. but I want to address this in a clean way.

**Comment by benas** [comment]
> I want to address this in a clean way

I'm not sure `FieldDefinition` can be used the same way for both field exclusion and randomizer registration. So I decided to keep it anyway (but [clearly document it](https://github.com/benas/random-beans/blob/e8152a63cb2a7804cf27cb94694bd4fb2ff67903/random-beans/src/main/java/io/github/benas/randombeans/EnhancedRandomBuilder.java#L80)) and fail fast at construction time (e8152a63cb2a7804cf27cb94694bd4fb2ff67903)

This is not very good in term of API design: A good API should prevent me form making errors, not let me make the error and throw an exception on my face saying that I should read the documentation ..
