### ISSUE TITLE
Have snapshot maven repo

### ISSUE THREAD

**Issue by dovidkopel** [benas/random-beans#161]
I would like to see a snapshot version available part of the automated build that reflects the most recent successful build of the snapshot version. This makes it possible for early adopters to use new features and play around with them without having to clone the repo. This is especially important when I am doing something using a snapshot feature I don't like to commit to my git repo knowing that if someone wants to build it will fail unless they have the snapshot version cached in their local repo.

**Comment by benas** [comment]
You don't have to clone the repo and build random beans locally. Snapshot are published after every successful build to sonatype's maven central snapshot repo: https://oss.sonatype.org/content/repositories/snapshots

See instruction on how to use snapshot version of random beans here: https://github.com/benas/random-beans/wiki/Getting-Started#maven-usage

basically just add the following repo:

```xml
<repository>
    <id>ossrh</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
</repository>
```

and import the snapshot version.

**Comment by dovidkopel** [comment]
Thanks!
