### ISSUE TITLE
Allow null values to be created

### ISSUE THREAD

**Issue by fedotxxl** [benas/random-beans#163]
I've got just the same question as #158 - how to add support to generate random null values?
You didn't answer it: `OptionalRandomizer` requires `delegate`. I tried to get delegate by calling `super.getRandomizer(field)` but it always null.

 ```
   private random = EnhancedRandomBuilder
            .aNewEnhancedRandomBuilder()
            .registerRandomizerRegistry(new CustomRandomizerRegistry() {
        @Override
        public Randomizer<?> getRandomizer(Field field) {
            def r = super.getRandomizer(field)

            if (field.type.isPrimitive()) {
                return r;
            } else {
                return new OptionalRandomizer(r, 10);
            }
        }
    })
            .build()
```

How to add random null support?

**Comment by benas** [comment]
Hi,

I think you don't need the `OptionalRandomizer` (unless you really want to use it). Here is the custom registry to use:

```java
@Priority(1)
public class CustomRandomizerRegistry implements RandomizerRegistry {

    @Override
    public Randomizer<?> getRandomizer(Field field) {
        if (shouldReturnNull()) { // implement the probability of how often to generate null
           return new NullRandomizer(); // the field will be set to null
        }
        return null; // this will use the "default" randomizer, and the field will be randomized
    }
}
```

Just implement the probability of how often to generate null in the `shouldReturnNull` method based on your requirements.

Give it a try and tell me what you think.

Kind regards
Mahmoud

**Comment by fedotxxl** [comment]
yes, it works but I think it would be useful to support it out of box
