### ISSUE TITLE
Add an option to not replace value in case of null

### ISSUE THREAD

**Issue by fedotxxl** [benas/random-beans#164]
This is related to #163
Suppose I've got `Job` class with `Set<Employee> employees = new HashSet<>();` field. If randomizer will return `null` default `HashSet` will be replaced with `null`. 

Is it possible to not replace default value in case of `null`? Something like  `DefaultValueOrNullRandomizer`

**Comment by benas** [comment]
Hi,

Just to make sure I understand your requirement, you have the following class:

```java
public class Job {
     private Set<Employee> employees = new HashSet<>();
}
```

and you ask random beans to generate a random instance of `Job`. What are you expecting to get in the `employees` field? An empty set?

As of version 3.1, random beans will randomize the `employees` field and I believe this is a bug (somehow related to [inline initialization](https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/FieldExclusionTest.java#L281). Inline initialization of fields should not be changed in regards to what the class designer has decided.

If I have the following class:

```java
@Data
    public static class BeanWithDefaultValues {
        Set<String> strings = new HashSet<>();
        List<Integer> integers = Arrays.asList(1, 2, 3);

        public BeanWithDefaultValues() {
            integers = Arrays.asList(1, 2, 3);
        }
    }
```

random beans will randomize both `strings` and `integers` fields and this is not what I'm expecting. The following test is failing with 3.1:

```java
@Test
public void inlineInitializationShouldNotBeChanged() {
        EnhancedRandom enhancedRandom = aNewEnhancedRandomBuilder().build();

        BeanWithDefaultValues bean = enhancedRandom.nextObject(BeanWithDefaultValues.class);

        assertThat(bean).isNotNull();
        assertThat(bean.getStrings()).isEmpty();
        assertThat(bean.getIntegers()).containsExactly(1, 2, 3);
}
```

So this should be the default behavior, not a configurable feature. Do you agree?

Kind regards
Mahmoud

**Comment by PascalSchumacher** [comment]
Hi Mahmoud,

I agree. Not overwriting fields values follows the principle of least surprise and should be the default.

**Comment by fedotxxl** [comment]
I always predefine `lists`/`maps` and etc (as I described before) to prevent `NullPointerException`. But I still want this fields to be randomized (as it works now). I think this is correct behavior.

>What are you expecting to get in the employees field? An empty set?
Sometimes empty set / sometimes set with random values. But not null value.

**Comment by benas** [comment]
Sorry, I still don't clearly understand

> Sometimes empty set / sometimes set with random values. But not null value.

I don't see how random beans can set this field to null. As of current version 3.1, it will randomize the field

> Is it possible to not replace default value in case of null?

what do you mean by "in case of null" ?

**Comment by fedotxxl** [comment]
Here is full example - https://gist.github.com/anonymous/ec5b65984524df99cd0438842e62c76b - I hope it will explain you an idea.

`DefaultValueOrNullRandomizer` will return `null` for `Article.tags` and `new HashSet<>()` for `ArticleWithDefault.tags`

**Comment by benas** [comment]
Ok I see, thank you for the example. This is a very specific requirement and I'm not sure it should be part of the library out of the box. Random Beans provides the `RandomizerRegistry` extension point specifically for this kind of custom requirements. So I suggest you use a custom registry for that.

BTW, @PascalSchumacher has kindly added support to override default initialization with the `overrideDefaultInitialization` parameter. You can try it out already with version 3.2.0-SNAPSHOT.

Kind regards
Mahmoud
