### ISSUE TITLE
Inconsistent stackmap frame

### ISSUE THREAD

**Issue by rakwaht** [benas/random-beans#179]
I am trying to use this tool in my project. So I added it into the pom file following the guide and I just tried to do the simplest thing that I could just to check if the dependency was working:
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder().build();

But during this call I have this error raised:
![error_benas](https://cloud.githubusercontent.com/assets/3703110/16735388/28ea514c-4789-11e6-9648-6c01577c23d1.PNG)

Anyway I am using java version "1.8.0_73" and Apache Maven 3.3.9. Let me know if you need some other information. I really don't know what to do (and actually this project was really useful to me). So hoping that is my mistake and not your bug I wait for your answer :)

Thanks, R.

**Comment by PascalSchumacher** [comment]
Hi rakwaht,

thanks for reporting.

Which random-beans version do you use. Which other libraries to do you use? Do you use any bytecode manipulation?

**Comment by rakwaht** [comment]
Hi pascal,

I am using last stable version of random-beans (3.2.0) and yes i am using Javassist for bytecode manipulation to inject some "tracking" callbacks int almost every method of every libraries. 

Actually I am not manipulating the classes of you library (I tried to blacklist them) but I think that can happen that I am injecting some code into classes that are not part of the package io.github.benas

![error_benas2](https://cloud.githubusercontent.com/assets/3703110/16757609/74f855e6-480d-11e6-8b5e-1e052414b58a.PNG)

Here is the new error after I blacklisted all the classes of the package io.github.beans (so they are not modified by my instrumentor). As you can see now the problem seems to be a static call that I actually think can be my instrumented code. But since I am sure that there is no injected code into your classes probably they are using some other libraries or generic constructs (e.g. java.util?)

**Comment by benas** [comment]
Hi @rakwaht 
Thank you for pointing out this issue.

> But since I am sure that there is no injected code into your classes probably they are using some other libraries or generic constructs (e.g. java.util?)

Looking at the location of your exception detail, the only static call (from `java.util.stream.Stream`) I see is here:

https://github.com/benas/random-beans/blob/master/random-beans/src/main/java/io/github/benas/randombeans/EnhancedRandomImpl.java#L80

Do you think this can be the cause of your issue?

**Comment by rakwaht** [comment]
Yes, this is the problem. I tried to blacklist all the package `java.util` and now the problem just moved to another package. Basically this means that this library is not compatible with my kind of injection and so I cannot use it for my purpose. 

Thanks a lot for helping me anyway. I'll star your project, you deserve it.
D.

**Comment by benas** [comment]
Thank you!
