### ISSUE TITLE
Option to force the creation of new objects / disable the use of existing instances

### ISSUE THREAD

**Issue by MarvinWyrich** [benas/random-beans#182]
Hi,

When randomizing an object with a list, I noticed that random-beans creates and puts around 10 new objects into a list and then starts to reuse existing objects, e.g. as the 11th element it puts a reference to object 3 into the list.

My problem is that I need to persist the randomized objects. After randomizing everything except the ID, I use Hibernate for assigning auto-generated (unique) IDs, but the 11th element will have the same ID as the 3rd, as they point to the same object. This causes a duplicate key exception.

I guess random-beans shows this behaviour for performance reasons, but is it (already) possible to force the creation of new objects?

**Comment by MarvinWyrich** [comment]
After getting deeper into the Code, the reason seems to be the `OBJECT_POOL_SIZE ` of `PopulatorContext` which is 10.

So I either need an option to disable caching at all or (some kind of workaround) to set the pool size by myself. Any thoughts on this? :)

**Comment by benas** [comment]
Hi, 

How come I didn't gave you a feedback earlier ?? I'm really sorry about that.

Yes, as you pointed out in [issue 186](https://github.com/benas/random-beans/issues/186#issuecomment-247379026), I'm planning to make the object pool size configurable.

I'll keep you informed once the addition is published.

Kind regards
Mahmoud

**Comment by PascalSchumacher** [comment]
@benas I'm just about to submit a pull request with this feature.

**Comment by PascalSchumacher** [comment]
Support for this was added with https://github.com/benas/random-beans/pull/196 Just set `maxObjectPoolSize` to a sufficiently big value.

**Comment by benas** [comment]
Hi @MarvinWyrich 

I've published version 3.3.0-SNAPSHOT which contains the fix for this issue (Many thanks to @PascalSchumacher for the patch).

You can set the object pool size with the `maxObjectPoolSize` parameter.

It would be great to give it a try and keep us informed if it's ok for you.

Kind regards
Mahmoud

**Comment by MarvinWyrich** [comment]
Thank you @benas and @PascalSchumacher.
Works fine!

**Comment by benas** [comment]
Cool. Thanks for taking time to test!
