### ISSUE TITLE
Enum values are not being randomized

### ISSUE THREAD

**Issue by pmaciocia** [benas/random-beans#184]
example:
```java
    private enum TestEnum {
        ONE, TWO, THREE, FOUR, FIVE;
    }

    private static void testEnum() {
        EnhancedRandom random = EnhancedRandomBuilder.aNewEnhancedRandomBuilder().build();

        for( int x=0; x<10; x++ ) {
            System.out.println(random.nextObject(TestEnum.class));
        }
    }
```
```
FOUR
FOUR
FOUR
FOUR
FOUR
FOUR
FOUR
FOUR
FOUR
FOUR
```

You can work around this by explicitly setting an EnumRandomizer for the enum
```
EnhancedRandom random = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
                .randomize(TestEnum.class, EnumRandomizer.aNewEnumRandomizer(TestEnum.class))
                .build();
```

From looking around the code it seems that the same seed is being reused for the EnumRandomizer each time, which would be fine if it was cached for each enum class.

**Comment by pmaciocia** [comment]
this is with version 'io.github.benas:random-beans:3.2.0'

**Comment by benas** [comment]
Hi,

Thank you for pointing out this issue, I was able to reproduce it.

I'll keep you informed once I publish the fix.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @pmaciocia 

The fix has been published in version 3.3.0-SNAPSHOT.

Could you please give it a try and keep me informed if it is ok for you?
Many thanks upfront.

Kind regards
Mahmoud

**Comment by pmaciocia** [comment]
Hi @benas,

Just tested and looks like it's working now. 

Thanks for making this project - its been very useful to me.

Peter

**Comment by benas** [comment]
Hi Peter,

Glad it helped! Thank you for reporting this issue.

Kind regards
Mahmoud
