### ISSUE TITLE
Support JPA relationships

### ISSUE THREAD

**Issue by dovidkopel** [benas/random-beans#185]
Support JPA relationship types as defined in https://en.wikibooks.org/wiki/Java_Persistence/Relationships.  This could be used to handle more complex relationships. This may require a tweak to how we handle recursion. Depends on https://github.com/benas/random-beans/issues/186

**Comment by benas** [comment]
I see, good idea indeed. Basically, using the same example in your link:

```java
@Entity
public class Employee {
  @Id
  private long id;
  
  @OneToMany
  private List<Phone> phones;

}

public class Phone {
    private Employee owner;
}
```

When I want a random instance of `Employee`, the field `phones` should be populated with instances of `Phone` having the `owner` set to the random instance of `Employee` being generated.

Simply put, the generated object graph should be valid according to JPA annotations.

Is this your feature request?

**Comment by benas** [comment]
Hi Dovid,

Even though the idea is really great as said previously, I'm afraid it will require a lot of work introspecting annotations of all JPA relationship types with recursivity and so on..

Hence, I'm not sure this feature should be added to random beans.
Thank you for your suggestion.

Kind regards
Mahmoud
