### ISSUE TITLE
how to limit the length of an array ?

### ISSUE THREAD

**Issue by oyxiaogua** [benas/random-beans#191]
hi:
      i'm using random-beans to generate javabean,how to configure to limit array field length?
      for example, String[] strArr, i want strArr.length less than 5.
      thanks.

**Comment by benas** [comment]
Hi,

This can be done using the `maxCollectionSize` parameter:

```java
EnhancedRandom enhancedRandom = aNewEnhancedRandomBuilder().maxCollectionSize(5).build();
String[] strArr = enhancedRandom.nextObject(String[].class);
assertThat(strArr.length).isLessThanOrEqualTo(5);
```

But this seems to be not working with arrays in version 3.2.0.

I'll fix that asap and keep you informed.
Thank you for reporting this issue.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @oyxiaogua 

The fix has been pushed to maven central in version 3.3.0-SNAPSHOT. Could you please give it a try and give us your feedback?

Many thanks to @PascalSchumacher for the fix.

Kind regards
Mahmoud
