### ISSUE TITLE
minimum size for string

### ISSUE THREAD

**Issue by alimohebbi** [benas/random-beans#192]
there is not any limitation in minimum size of random string. sometimes this method return a character
random.nextObject(String.class);

**Comment by benas** [comment]
Yes, `random.nextObject(String.class);` may generate strings of length 1. There is a parameter to set the maximum string length (`maxStringLength`) but not the min length.

**Comment by alimohebbi** [comment]
yes i know that thera is not any min limit, but i think it can be a good feature to add. it was necessary for me in my project and maybe other people need it too.

**Comment by benas** [comment]
That's fine.

Let's plan this feature for next release.

I'll keep you informed once the addition is published.

Kind regards
Mahmoud

**Comment by alimohebbi** [comment]
thanks a lot .

**Comment by benas** [comment]
Hi @alimohebbi 

Support for `minStringLength` parameter has been added in version 3.3.0-SNAPSHOT. Can you please give it a try?

Kind regards
Mahmoud

**Comment by alimohebbi** [comment]
hi
i could not find v 3.3.0 in release tab on git. how can import it in my
pom.xml ?

**Comment by benas** [comment]
v3.3.0 is not yet released. The fix is published in the snapshot version. you need to add sonatype snapshot repo in your pom. You can find details in [the wiki](https://github.com/benas/random-beans/wiki/Getting-Started#maven-usage)

**Comment by benas** [comment]
I'm preparing release v3.3. Keep tuned
