### ISSUE TITLE
Minimum size for HashMap Item

### ISSUE THREAD

**Issue by alimohebbi** [benas/random-beans#197]

**Comment by benas** [comment]
Hi, 

As seen in #198 , the size of maps can be limited with the `maxCollectionSize` parameter. For min size, I suggest to first add a `minCollectionSize` parameter and then introduce the `collectionSizeRange` (as [proposed](https://github.com/benas/random-beans/issues/198#issuecomment-247760405))  in a future release.

Will keep you informed once the addition is published.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @alimohebbi 

The `minCollectionSize` parameter has been added in version 3.3.0-SNAPSHOT (Many thanks to @PascalSchumacher for this addition).

It would be great to give it a try and keep us informed if it's ok for you.

Kind regards
Mahmoud

**Comment by MarvinWyrich** [comment]
Hi @benas @PascalSchumacher,

For me it looks like the implementation of getRandomCollectionSize() in EnhancedRandomImpl.java is not correct.
1) if you set the minimum size to the same value as the maximum size (= you want to specify an exact collection size), the collecton size will be between 0 and the minCollectionSize (exclusively).
2) `return nextInt(maxCollectionSize - minCollectionSize) + maxCollectionSize; `
Let's take for example min: 2 and max: 3. The method will then always return 3.

**Comment by PascalSchumacher** [comment]
Hi @MarvinWyrich 

thanks for the feedback. :+1: 

You are right, my implementation of `EnhancedRandomImpl#getRandomCollectionSize` was completely wrong. :( It should be fixed by: https://github.com/benas/random-beans/commit/db89c39ac698a00a49f231adfec10c24b55c094a

**Comment by benas** [comment]
@MarvinWyrich Thank you for your feedback
@PascalSchumacher Thank you for the fix

Open source is just amazing 😄 

@alimohebbi It would be great to have your feedback on the feature you requested. I'm preparing to release v3.3 soon
