### ISSUE TITLE
Maximum Size For HashMap Elements

### ISSUE THREAD

**Issue by alimohebbi** [benas/random-beans#198]
There is no limit on populating a hashmap. random created hashmap can have any number of elements and this method "EnhancedRandomBuilder.aNewEnhancedRandomBuilder().maxCollectionSize(n)" do nothing about it.

**Comment by PascalSchumacher** [comment]
MaxCollectionSize should be respected for maps. Can you please provide a test to demonstrate the bug?

**Comment by benas** [comment]
Hi @alimohebbi 

In Java, a Map is not a Collection. So you can't really control map size using `maxCollectionSize`. This would be inconsistent.

If random beans should provide such a feature, it should be done using a separate parameter. Probably `maxMapSize`. Or since you request min and max sizes, why not do it in the same way as integer/date ranges for consistency:

```
EnhancedRandom random = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
   .collectionSizeRange(1, 10)
   .stringLengthRange(5, 20)
   .mapSizeLength(0, 50)
   .dateRange(today, tomorrow)
   .timeRange(nine, five)
   .build();
```

What do you think?

**Comment by PascalSchumacher** [comment]
@benas 
https://github.com/benas/random-beans/blob/master/random-beans/src/main/java/io/github/benas/randombeans/MapPopulator.java#L55 ->
https://github.com/benas/random-beans/blob/master/random-beans/src/main/java/io/github/benas/randombeans/EnhancedRandomImpl.java#L165

So `maxCollectionSize` is used for maps at the moment. Or I'm I missing something?

I guess @alimohebbi used a static method (which does not use the configuration) to populate the object.

**Comment by benas** [comment]
Thank you Pascal. Indeed, this is the current state, but it is a design issue in random beans IMO. I think we're getting a lot of minXXX, maxXXX parameters. They should be all replaced with ranges for consistency. I would like to profit from this issue to fix that.

**Comment by PascalSchumacher** [comment]
Sure. I think ranges would be nice indeed. :)

I just wanted to point out the feature requested in this issue already exists.

I do not think to using maxCollectionSize for maps is a design mistake. Maps and Arrays do not implement the Collection interface but the are collections, so I think it's o.k. to use maxCollectionSize also for maps and arrays as Random Beans currently does.

**Comment by benas** [comment]
You are right, even though technically speaking a Map is not a Collection, the parameter can be used for maps too. And since there is a user who expected that `maxCollectionSize` would limit a HashMap size (like in the current issue), I can't say there is a design issue 😉 .

@alimohebbi Could you please provide an example to help us reproduce the problem?

**Comment by alimohebbi** [comment]
@benas yes of course , here is a simple example. when i use randomListOf method hashmap in elements of generated list are more than max size.

`public class HashMapTest {
    private EnhancedRandom dummyCreator;

    @Before
    public void setup() {
        dummyCreator = EnhancedRandomBuilder
                .aNewEnhancedRandomBuilder()
                .scanClasspathForConcreteTypes(true)
                .maxCollectionSize(5)
                .seed(19212)
                .build();
    }


    @Test
    public void test() {
        List<MyHashMap> myHashMap = dummyCreator.randomListOf(10, MyHashMap.class);
        
    }
}
`
`public class MyHashMap {

    private Map<String, String> data;

    public Map<String, String> getData() {
        return data;
    }

    public void setData(Map<String, String> data) {
        this.data = data;
    }
}
`

**Comment by PascalSchumacher** [comment]
@alimohebbi Thanks for the example.

The configuration does not effect the ***static*** methods of `EnhancedRandom` like `randomListOf`.

The instance methods `nextObject` and `objects` use the configuration.

**Comment by alimohebbi** [comment]
nextObject works fine. thanks for your help. 
i didn't read anything about configuration doesn't affect static methods in documentation; however it seem to be logical. maybe i didn't read well.  ;)

**Comment by benas** [comment]
No problem. It's in the [home page](https://github.com/benas/random-beans/wiki#what-is-this-enhancedrandom-api) of the wiki:

"In most cases, default options are enough and you can use a static import of the EnhancedRandom.random(Class object) as seen previously."
