### ISSUE TITLE
MapRandomizer sometimes fails because "random number of entries = 0"

### ISSUE THREAD

**Issue by vanhove** [benas/random-beans#199]
Hi,

We found a small bug in the MapRandomizer class:

`
public MapRandomizer(final Randomizer<K> keyRandomizer, final Randomizer<V> valueRandomizer) {
     this(keyRandomizer, valueRandomizer,  abs(aNewByteRandomizer().getRandomValue()));
  }
`

The ByteRandomizer can return the value 0 causing the MapRandomizer to fail:
`
private void checkArguments(final int nbEntries) {
        if (nbEntries < 1) {
            throw new IllegalArgumentException("The number of entries to generate must be >= 1");
        }
    }
`

**Comment by benas** [comment]
Hi,

Thank you for reporting.

I'll fix the issue asap and keep you informed.

Kind regards
Mahmoud

**Comment by PascalSchumacher** [comment]
@benas: I fixed the issue. I hope you do not mind. Fell free to change anything if you prefer a different solution.

**Comment by vanhove** [comment]
@PascalSchumacher: thanks for fix!

@benas: The world is small, I didn't know that this was a side project of you,  give my greetings to all the colleagues,  Hannes

**Comment by benas** [comment]
@PascalSchumacher Thank you for the fix. You rock!

> The world is small, I didn't know that this was a side project of you, give my greetings to all the colleagues, Hannes

Hey Hannes! Thank you. Indeed, the world is small 😄 

>give my greetings to all the colleagues, Hannes

Sure!

I've deployed the fix to maven central, please don't hesitate to reopen the issue in case of any problem.

Kind regards
Mahmoud
