### ISSUE TITLE
Options for control recursion

### ISSUE THREAD

**Issue by sansherbina** [benas/random-beans#206]
Hi,
I have class A, which have field of type A. For control this recursion, library provides caching and control cache size. But, I have cases, when I don't want have cycles. Because, for example JAXB crash if object has cycle. (Cycle I mean, when object A have link on himself directly or through second object).
I would like to propose next approache, how to handle this issue.
In PopulatorContext in method getPopulatedBean always return new instance, but calculate how many instances already created. And if border exceeded return null.
Also, for avoid problems with nulls in collection, we need to add checks on nulls. At least for MapPopulator. Because, TreeMap with default comparator, does not support null keys. And right now exists bug, when custom Randomizer return null, and this value setted to TreeMap, we get exception.

**Comment by sansherbina** [comment]
Guys what do you think? If you are agree with it, I can contribute, this changes are important for me

**Comment by PascalSchumacher** [comment]
So basically you like to add an option which prevents the creation of cycles in the object graph?

**Comment by sansherbina** [comment]
Yes, but if this option will be turned on we will get next situation. For example option "cache size"=3. And we have class "class A{private A a;}". So we will have 3 instances of A, and the last one will have field a with null value.

**Comment by benas** [comment]
Hi, I see. You are welcome to contribute this addition.

> right now exists bug, when custom Randomizer return null, and this value setted to TreeMap, we get exception.

please open a separate issue for this case.

**Comment by benas** [comment]
Is this a duplicate of `ObjectPoolSize` and `RandomizationDepth` parameters?

I think with a combination of these 2 parameters, we can already control recursion and avoid cycles in object graph, here is a good example: https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/EnhancedRandomImplTest.java#L384

Do you agree? Please forgive me, probably I've missed something..

**Comment by sansherbina** [comment]
Yes, you are right, we resolved problem with nulls in collection, so we can use ObjectPoolSize and RandomizationDepth to control recursion. So, I believe, we can close this issue.
