### ISSUE TITLE
Object initialization depth

### ISSUE THREAD

**Issue by sansherbina** [benas/random-beans#207]
Hi,
For complicated objects with big amount of fields, when fields also have big amount of fields, I think, good to have any option which will control depth of initialization. For example, when set depth 2, initialized only Root object and his fields, but fields of fields are null.
By default this option might be turned off.

**Comment by sansherbina** [comment]
Guys what do you think? If you are agree with it, I can contribute, this changes are important for me

**Comment by PascalSchumacher** [comment]
I think this is a good idea.

**Comment by benas** [comment]
Hi,

Indeed, this is a good idea. You are welcome to contribute to the project!

Kind regards
Mahmoud

**Comment by benas** [comment]
@sansherbina I'm closing this issue since your PR was merged.

Many thanks!
Kind regards
Mahmoud
