### ISSUE TITLE
ClassCastException on wildcard generics in collections

### ISSUE THREAD

**Issue by ryber** [benas/random-beans#208]
Hello, Trying to figure out the best way around this. I want to populate some JAX-B beans. They have fields like this:

`@XmlElementRef(name = "reportedLocation", namespace = "http://api.foo.com/v3", type = JAXBElement.class)
    protected List<JAXBElement<? extends ReportedLocation>> reportedLocations;`

I get a ClassCastException exception from this:

`Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
    at io.github.benas.randombeans.CollectionPopulator.getRandomCollection(CollectionPopulator.java:68)
    at io.github.benas.randombeans.FieldPopulator.generateRandomValue(FieldPopulator.java:93)
    at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:79)
    at io.github.benas.randombeans.EnhancedRandomImpl.populateField(EnhancedRandomImpl.java:162)
    at io.github.benas.randombeans.EnhancedRandomImpl.populateFields(EnhancedRandomImpl.java:153)
    at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:124)
    ... 203 more`

There are quite a few of these. I have a custom registry for some other abstract classes I have but I'm unsure of the best way around this one.

Another suggestion, it might be nice if the EnhancedRandom were to have a brute force mode where it never ever stops for these kinds of errors and just skips them (and logs an error maybe) 

Great library everyone!

**Comment by benas** [comment]
Hi,

Thank you for reporting this issue!

We will keep you informed once the fix is published.

Kind regards
Mahmoud

**Comment by enedzvetsky** [comment]
I have the same error and tried this fix. ClassCastException was fixed but collection is empty.
I attached test.
[rbeans_param_map.zip](https://github.com/benas/random-beans/files/559529/rbeans_param_map.zip)

**Comment by PascalSchumacher** [comment]
@enedzvetsky Thanks. That the collection is empty is the expected behavior. Trying fill it would require significantly more coding effort.

**Comment by benas** [comment]
Hi @ryber ,

We have published the fix in the latest 3.4.0-SNAPSHOT version.
Could you please give it a try? ClassCastException should be fixed now.

> Another suggestion, it might be nice if the EnhancedRandom were to have a brute force mode where it never ever stops for these kinds of errors and just skips them (and logs an error maybe)

I see, probably a "silent mode" parameter where errors are logged but the randomization continues.
Or may be the other way, where silent mode is the default and add a "strict mode" parameter that stops randomization on first error. What do you think? Please open a separate issue for this request.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @ryber @enedzvetsky 

v3.4 has been released with the fix.
Please reopen this issue in case of any problem.

Many thanks to @PascalSchumacher for the fix!

Kind regards
Mahmoud
