### ISSUE TITLE
MapPopulator doesn't support java.util.EnumMap

### ISSUE THREAD

**Issue by enedzvetsky** [benas/random-beans#211]
MapPopulator doesn't support java.util.EnumMap. 
MapPopulator.java:66 produces EnumMap without EnumMap#keyType field.
New instance of EnumMap should be created only with constructor with keyType 
So MapPopulator for EnumMap should use
Type keyType = parameterizedType.getActualTypeArguments()[0];
or return null value.

**Comment by benas** [comment]
Hi,

Thank you for reporting this issue!

Could you please give an example of how to reproduce it?
Will try to fix it asap.

Kind regards
Mahmoud

**Comment by enedzvetsky** [comment]
[rbeans_enummap_test.zip](https://github.com/benas/random-beans/files/559323/rbeans_enummap_test.zip)

**Comment by benas** [comment]
Thank you for the example. I'm able to reproduce the issue.
Will fix it asap and keep you informed.

Kind regards
Mahmoud

**Comment by benas** [comment]
I've deployed the fix in 3.4.0-SNAPSHOT.
Could you please give it a try and tell me if it is ok for you?

Many thanks upfront!

**Comment by enedzvetsky** [comment]
Fantastically quick response. :)
I checked on real project. It's working now.

**Comment by benas** [comment]
Glad it helped!
Will plan the fix for next release.
