### ISSUE TITLE
Flexible FieldExclusionChecker

### ISSUE THREAD

**Issue by enedzvetsky** [benas/random-beans#212]
Current version doesn't support exclusion by some specific rules. So current API doesn't support custom FieldExclusionChecker.
For example I use  random-beans for custom serialization/de-serialization testing and I want to exclude all transient fields. 
It's very simple to create custom ProjectFieldExclusionChecker with additional check for isTransient but ...

**Comment by benas** [comment]
Indeed, that's not very flexible as is.

I was thinking of making the `FieldDefinition` more flexible by taking into account modifiers:

```java
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
 .exclude(FieldDefinitionBuilder.field()
   .named("age")
   .ofType(Integer.class)
   .inClass(Person.class)
   .withModifier(Modifier.TRANSIENT)
   .get())
   .build();
```

This will exclude a specific transient field (can exclude all transient fields by omitting other criteria).

What do you think?

**Comment by enedzvetsky** [comment]
Your solution is more clear for Random-beans API.
It will work for my project.

**Comment by benas** [comment]
Ok, will try to come up with this feature asap.

BTW, you can use a custom registry for that:

```java
import io.github.benas.randombeans.api.EnhancedRandomParameters;
import io.github.benas.randombeans.api.Randomizer;
import io.github.benas.randombeans.api.RandomizerRegistry;
import io.github.benas.randombeans.randomizers.misc.NullRandomizer;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;

public class TransientFieldRandomizerRegistry implements RandomizerRegistry {
    @Override
    public void init(EnhancedRandomParameters parameters) {
         //  no op
    }

    @Override
    public Randomizer<?> getRandomizer(Field field) {
        if (Modifier.isTransient(field.getModifiers())) {
            return new NullRandomizer();
        }
        return null;
    }

    @Override
    public Randomizer<?> getRandomizer(Class<?> type) {
        return null;
    }
}
```

This registry tells random bean to not touch transient field.
Registries are powerful because they give you access to the field being randomized, hence you can add any behaviour you want (in this case, exclude transient fields).

Just register the above registry and all transient fields will be excluded.

Please let me know if this helped.
Kind regards
Mahmoud

**Comment by enedzvetsky** [comment]
Thank you. I implemented transient fields in this way a few minutes ago.

**Comment by sansherbina** [comment]
Created PR for this feature https://github.com/benas/random-beans/pull/215
Benas, I hope, I haven't started implement it yet)

**Comment by benas** [comment]
Hi @enedzvetsky ,

@sansherbina has kindly added support for field exclusion by modifiers (see the new `hasModifiers` method in `FieldDefinitionBuilder`). Thank you @sansherbina !

I've deployed 3.4.0-SNAPSHOT version to maven central with this addition.

Could you please give it a try and keep us informed if this is ok for you?

Kind regards
Mahmoud

**Comment by enedzvetsky** [comment]
Hi @benas ,
It works fine. Thank you.
Thank you very much @sansherbina

**Comment by benas** [comment]
Good news 😄 

Open source community is wonderful, really!

I'll release 3.4 soon, keep tuned.

My best regards
Mahmoud
