### ISSUE TITLE
Null keys not supporter by TreeMap, ConcurrentHashMap, ConcurrentSkipListMap

### ISSUE THREAD

**Issue by sansherbina** [benas/random-beans#213]
MapPopulator create new instance of Map interfaces. If Map is generic, MapPopulator populate it - create random key and random value. If random key is null, then we get exception, because ConcurrentSkipListMap, ConcurrentHashMap, TreeMap are not support null keys.
I suggest to check if map instance is not HashMap instance, then don't add null keys to it,

**Comment by sansherbina** [comment]
Here is PR for this bug https://github.com/benas/random-beans/pull/214

**Comment by benas** [comment]
Hi Olexandr,

Thank you for pointing this out and for your PR! The problem is here:

> If random key is null, then we get exception, because ConcurrentSkipListMap, ConcurrentHashMap, TreeMap are not support null keys.

Looking at the code, the `enhancedRandom` instance is used to generate keys, it should not generate null values at all. The only case I see is when the user provides the NullRandomizer for the map key type.

> I suggest to check if map instance is not HashMap instance, then don't add null keys to it,

IMO, we should not allow adding nulls in keys even for hash maps, there is no added value for null keys.
Do you agree?

Kind regards
Mahmoud

**Comment by sansherbina** [comment]
Hi Benas,
Yes I agree, that this situation possible only if user use NullRandomizer. But this situation is still possible for me.
And yes, I agree, to not put null keys at all for all maps.
I will change my PR.

**Comment by sansherbina** [comment]
Updated PR https://github.com/benas/random-beans/pull/214
When do you plan next release?

**Comment by benas** [comment]
> Yes I agree, that this situation possible only if user use NullRandomizer. But this situation is still possible for me.

Yes this what I meant, this case is still possible when the user explicitly registers a NullRandomizer for the map key type. So adding the null check on the key as you did is the way to go.

**Comment by benas** [comment]
> When do you plan next release?

I was planning to implement issues 188 and 212 and then release v3.4.0

I'm not sure to have time to finish them soon, so may be I'll release 3.4 in the next few days and keep them for 3.5

I'll keep you informed in both case :smile: 
Mahmoud

**Comment by benas** [comment]
Hi @sansherbina ,

v3.4 has been released, enjoy 😉 

Thank you for your contribution!

Kind regards
Mahmoud
