### ISSUE TITLE
Support customization for internal randomizers.

### ISSUE THREAD

**Issue by enedzvetsky** [benas/random-beans#216]
Some randomizers contain another randomizers. For example OffsetDateTimeRandomizer contains next randomizers:
localDateRandomizer = new LocalDateRandomizer();
localTimeRandomizer = new LocalTimeRandomizer();
zoneOffsetRandomizer = new ZoneOffsetRandomizer();

I would like to customize only ZoneOffsetRandomizer.
Is it possible to change Random-beans code and get these internal randomizers from RandomizerRegistry? 
localDateRandomizer = randomizerRegistry.getRandomizerByType(LocalDate.class);
localTimeRandomizer = randomizerRegistry.getRandomizerByType(LocalDateTime.class);
zoneOffsetRandomizer = randomizerRegistry.getRandomizerByType(ZoneOffset.class);

**Comment by benas** [comment]
Sorry for the late reply, I'll come back to you asap.

**Comment by benas** [comment]
Hi,

> I would like to customize only ZoneOffsetRandomizer.

 I see.

> Is it possible to change Random-beans code and get these internal randomizers from RandomizerRegistry?
localDateRandomizer = randomizerRegistry.getRandomizerByType(LocalDate.class);

I'm not sure, we don't have a randomizeRegistry in the scope.
What about adding a constructor to provide custom collaborators?

**Comment by enedzvetsky** [comment]
Hi.

New constructor is Ok. Thanks.

**Comment by benas** [comment]
Hi @enedzvetsky 

I've added setters for delegate randomizers to be able to use custom collaborators.

I've suggested to add constructors parameters, but I think it's better to use constructors parameters for required dependencies and setters for optional dependencies. So I preferred to add setters here.

version 3.5.0-SNAPSHOT contains new setters where appropriate.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @enedzvetsky 

Have you been able to customize your randomizer with new setters?

I would like to see if this is ok to include it in the upcoming release.

Kind regards
Mahmoud

**Comment by enedzvetsky** [comment]
Sorry, I'm on vacation. I'll check it 01/30. 
Thanks for your work.

**Comment by benas** [comment]
No worries, enjoy your holidays!

**Comment by enedzvetsky** [comment]
Looks good, It's working for me.
Thanks.

**Comment by benas** [comment]
Great! Just in time, I'm releasing v3.5 this weekend.
