### ISSUE TITLE
Support substitution of types

### ISSUE THREAD

**Issue by johanhaleby** [benas/random-beans#217]
I run into an issue where random beans can't create a random value for my interface defined like this: 

```java
public interface MyConstraint<V> {
    String getName();
    String getGroup();
    V getValue();

    default <T extends MyConstraint<V>> T as(Class<T> constraintType) {
        return constraintType.cast(this);
    }
}
```

I'd like to just be able to substitute this interface for an implementation. For example:

```java
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
                .substitute(MyConstraint.class, MyConstraintImpl.class).build();
```

where `MyConstraintImpl` is one of the implementations defined in my code (which random beans _can_ cope with).

**Comment by benas** [comment]
Hi Johan,

I'm happy to see you here :smile: I'm in love with rest assured! Congrats.

Have you tried to activate the `scanClasspathForConcreteTypes` parameter? RB will try to find an implementation of your interface and generate a random instance for it.

Another way is to explicitly provide a randomizer:

```java
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
                .randomize(MyConstraint.class, new MyConstraintImplRandomizer()).build();
```

with `MyConstraintImplRandomizer` implementing random instance creation.

Hope this helps,
Kind regards
Mahmoud

**Comment by johanhaleby** [comment]
> I'm happy to see you here 😄 I'm in love with rest assured! Congrats.

Wow thanks :) I'm really digging this library as well so far (but it's the first time I'm using it so sorry if I'm missing something obvious).

 > Have you tried to activate the scanClasspathForConcreteTypes parameter?

I just tried this but I get the same error. But I've already managed to workaround it be using a `Randomizer` just like you're suggesting. I actually think that's good enough.
