### ISSUE TITLE
EnhancedRandomImpl.getRandomCollectionSize never returns maxCollectionSize

### ISSUE THREAD

**Issue by kermit-the-frog** [benas/random-beans#220]
Hi

`return nextInt(maxCollectionSize - minCollectionSize) + minCollectionSize;`

gives only values between minCollectionSize and maxCollectionSize - 1

Kind regards,
Kermit_the_frog

**Comment by PascalSchumacher** [comment]
Thanks for reporting! 👍

**Comment by benas** [comment]
@kermit-the-frog Thank you for reporting this issue.

@PascalSchumacher Thank you for the quick fix!

Best regards
Mahmoud
