### ISSUE TITLE
Beans with fields like JAXBElement<?> - java.lang.IllegalAccessError: java.lang.Class

### ISSUE THREAD

**Issue by dermoritz** [benas/random-beans#221]
If i try to create a random bean of a JAXB annotated class that conatins fields of type JAXBElement<> i get an not very verbose exception:

"java.lang.IllegalAccessError: java.lang.Class"

First of all i would suggest a better message like "could not create object of class JAXBElement for field xyz"

Is there any way to create random objects of such classes? I don't want to set those fields manually. 
Is there a way to provide factory methods or classes that are used if randombeans hits a field with such a type?

**Comment by PascalSchumacher** [comment]
Thanks for reporting!

As far as I know `JAXBElement`s can not be directly instantiated by a default constructor, an object factory (or a special `JAXElement` constructor with namespace etc.) has be used, see e.g. http://stackoverflow.com/questions/975099/how-do-i-instantiate-a-jaxbelementstring-object

Random Beans is not aware of any of this, so it first tries to create a JAXBlement by using reflection and then by using the objenesis library. Both ways fail.

You could implement and register a custom randomizer (https://github.com/benas/random-beans/wiki/Key-APIs) for `JAXBElement`s. See https://github.com/benas/random-beans/blob/12cdf5da8b659bf5a3e76d0e590ccd9eab243e24/random-beans/src/test/java/io/github/benas/randombeans/EnhancedRandomImplTest.java#L176 for an example.

**Comment by dermoritz** [comment]
Thanks, that is what i was looking for .

Then the only thing left is, that random beans could give a better exception in such cases!?

**Comment by benas** [comment]
Hi @dermoritz 

Indeed, Random Beans should provide a better error message!

Could you please give me an example of the bean you are trying to randomize?

Kind regards
Mahmoud

**Comment by PascalSchumacher** [comment]
New error message will be:

```
io.github.benas.randombeans.api.ObjectGenerationException: Unable to generate a random instance of type class io.github.benas.randombeans.Tester$JaxbElementBean
Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to create type: javax.xml.bind.JAXBElement for field: jaxbElementField of class: io.github.benas.randombeans.Tester$JaxbElementBean
```

@dermoritz thanks for reporting this. 👍 I think this is a major improvement for random-beans error reporting. :)
