### ISSUE TITLE
Issue with collection size 

### ISSUE THREAD

**Issue by sunnyg522** [benas/random-beans#224]
we have a very complex object with close to 500+ attributes and we are using configuration .maxCollectionSize(1)  and maxRandomizationDepth(3)
dose maxCollectionSize or maxRandomizationDepth(3) restrict the array size also or is their a different setting for it? 
if maxCollectionSize or maxRandomizationDepth(3) takes care of array size, we still see some nested objects with array size greater than 1 and eventually going more than 100 , which is causing memory issues at our end. Is their a way how we can control array size ?

**Comment by PascalSchumacher** [comment]
Hi @sunnyg522,

`maxCollectionSize` is also used for array size.

How exactly do you use `EnhancedRandom`? The configuration is only used by the instance methods (not by the static methods) of this class.

**Comment by benas** [comment]
Hi @sunnyg522 

> dose maxCollectionSize or maxRandomizationDepth(3) restrict the array size also or is their a different setting for it?

As @PascalSchumacher said, you can use the `maxCollectionSize` to restrict arrays size as well.
You can find an example [here](https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/EnhancedRandomBuilderTest.java#L155).

`maxRandomizationDepth` is used to limit the level of object graph to randomize.

Please find more details for each parameter in the [wiki](https://github.com/benas/random-beans/wiki/Randomization-parameters).

Hope this helps.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @sunnyg522 

Have you been able to use the `maxCollectionSize` parameter to limit array size?

Kind regards
Mahmoud

**Comment by benas** [comment]
Any update on this?

**Comment by sunnyg522** [comment]
@benas yes i am able to create object with aNewEnhancedRandomBuilder function, before i was using random. now i am good and random objects are getting created perfectly. Thanks for the follow up.

**Comment by benas** [comment]
Great, thank you.
