### ISSUE TITLE
get a random element inside a subset of an enumeration's values

### ISSUE THREAD

**Issue by euZebe** [benas/random-beans#239]
Hi,

Regular user of random beans for a few weeks, I would appreciate to find a utility class so that I can get a random element among an enumeration values, possibly excluding some values.

What do you think of it ?

I quickly suggested a pull request, but looking deeper inside the library, I think I should refactor it a bit so that it is more consistent with the rest of the code.

**Comment by benas** [comment]
Hi,

Thank you for this suggestion and for your PR.

Have you considered extending/decorating the existing `EnumRandomizer` to add this custom need?
I'm not sure this should be added to the EnhancedRandom API as a new method.

What do you think?

Kind regards
Mahmoud

**Comment by benas** [comment]
I was thinking of adding a new constructor in [EnumRandomizer](https://github.com/benas/random-beans/blob/master/random-beans/src/main/java/io/github/benas/randombeans/randomizers/misc/EnumRandomizer.java):

```java
    public EnumRandomizer(final Class<E> enumeration, final E... excludedValues) {
        ...
    }
```

and implement the exclusion logic in this class. What do you think?

**Comment by euZebe** [comment]
Sounds perfect !
I admit I had not noticed that EnumRandomizer. I move and adapt the code in it and suggest a new pull request.

**Comment by euZebe** [comment]
[pull request created](https://github.com/benas/random-beans/pull/238)

**Comment by benas** [comment]
Oh great! many thanks.

I'll take a look asap.

Kr
Mahmoud

**Comment by benas** [comment]
Hi,

I've added a couple of notes in the PR.
Please have a look and tell me what you think.
If you agree, don't hesitate to update it and it will be ok to merge.

Kind regards
Mahmoud

**Comment by euZebe** [comment]
Hi,
I don't see any note in the PR (maybe I don't look at the right place ; I am not very used to GitHub and pulling requests).

**Comment by benas** [comment]
oops sorry, forgot to submit reviews.
Those are a couple of minor changes.

Thank you in advance

**Comment by euZebe** [comment]
Changes commited ; I agree with everything.

**Comment by benas** [comment]
Hi,

Thank you for these update.

I've merged the PR.

Thank you for your contribution 👍 

Kind regards
Mahmoud

**Comment by euZebe** [comment]
Hi,
When is planned the next release of random-beans, please ?
I would like to use the current feature but I'd rather not use a snapshot version.

Kind regards

**Comment by benas** [comment]
Hi,

I've planned to release v3.6 by the end of this week.

Keep tuned.

Kind regards
Mahmoud

**Comment by benas** [comment]
As promised, v3.6 is [out](https://github.com/benas/random-beans/releases/tag/random-beans-parent-3.6.0). Thank you for your addition. Enjoy 😉
