### ISSUE TITLE
protected constructor

### ISSUE THREAD

**Issue by pgaschuetz** [benas/random-beans#246]
When populating a new bean, ObjectFactory.createNewInstance creates a new instance either by calling the public default constructor or falling back to Objenisis.
I'm sure there are reasons for this - I cannot judge.
However, this can have some interesting side-effects.

Consider the following
```
public class Book {
  private UUID id = UUID.randomUUID();
  private String title;

  protected Book() {}

  public Book (String title) {
    this.title = title;
  }
}
```

ObjectFactory.createNewInstance falls back to Objenisis. Objenisis instantiates without calling any constructor, also the id field never gets initialized.

I would like to propose to try to create a new instance by first making a non-accessible constructor accessible before falling back to Objenisis - or at least make it configurable.
This would align behaviour with JPA/Hibernate.

```
    private <T> T createNewInstance(final Class<T> type) {
        try {
		Constructor c = type.getDeclaredConstructor();
		if(! c.isAccessible())
			c.setAccessible(true);
		return c.newInstance();
        } catch (Exception exception) {
            return objenesis.newInstance(type);
        }
    }
```

**Comment by PascalSchumacher** [comment]
Sounds like a good idea to me.

**Comment by PascalSchumacher** [comment]
The id in your example is not initialized during object construction but random-beans will initialize the field by randomizing it.

If it was initialized during object construction random-beans would overwrite the field value with a random value, unless the field is explicitly excluded from randomization.

In fact object creation by reflection was added for https://github.com/benas/random-beans/issues/84 to let excluded fields be initialized by the default constructor.

**Comment by pgaschuetz** [comment]
Yes, that's true, but in fact I stumbled upon it while excluding it.

What I did:
* A class with a default initialized field and a protected constructor (as in the example above)
* .overrideDefaultInitialization(false)

--> leads to empty id

**Comment by benas** [comment]
> When populating a new bean, ObjectFactory.createNewInstance creates a new instance either by calling the public default constructor or falling back to Objenisis.
> I'm sure there are reasons for this - I cannot judge.
> However, this can have some interesting side-effects.

I do confirm. Here are some interesting side effects we are aware of:

[https://github.com/benas/random-beans/blob/master/random-beans/src/main/java/io/github/benas/randombeans/ObjectFactory.java#L84](https://github.com/benas/random-beans/blob/master/random-beans/src/main/java/io/github/benas/randombeans/ObjectFactory.java#L84)

> I would like to propose to try to create a new instance by first making a non-accessible constructor accessible before falling back to Objenisis

That's fine. After all, with these kind of libraries (random beans, objenesis and alike), we are torturing client classes as we want using reflection: making private things public, accessing non-accessible constructors, everything the class designer have never imagined we would do with his class.. All this torture/surgery is possible today thanks (or due?) to reflection which clearly breaks encapsulation and will disappear with Java 9 modules..

Anyway, @PascalSchumacher has kindly added support for your feature request.
I'll plan it for next release. Keep tuned. Thank you Pascal!

**Comment by pgaschuetz** [comment]
thanks!

**Comment by benas** [comment]
@pgaschuetz I've deployed v3.7.0-SNAPSHOT with the new feature. Could you please give it a try and tell us if this is ok for you?

Many thanks upfront.

**Comment by pgaschuetz** [comment]
looking good to me!
thanks!

**Comment by benas** [comment]
Great, thanks.

**Comment by pgaschuetz** [comment]
Hi,

would it be possible to make a v3.7.1 release?

**Comment by pgaschuetz** [comment]
uum... sorry, I mean 3.6.1 or 3.7.0 :-)

**Comment by benas** [comment]
Hi,

I'll try to release v3.7 this weekend.
I'll let you know.

Kr
Mahmoud

**Comment by benas** [comment]
Hi @pgaschuetz 

FYI, v3.7 is released with the fix for this issue.

Enjoy!

Kr
Mahmoud
