### ISSUE TITLE
Generate test fixtures using a JUnit rule/runner

### ISSUE THREAD

**Issue by benas** [benas/random-beans#251]
Sometimes, the test fixture does not really matter to the test logic. For example, if we want to test the result of a new sorting algorithm, we can generate the input data and assert the output is sorted, regardless of the data itself. Another example is testing the persistence of domain object, we can generate the domain object, persist it and assert the database contains the same values.

The idea is to use random beans to generate random test fixtures using a junit rule:

```java
public class Test {

    @Rule
    private RandomFixtureRule randomFixtureRule = new RandomFixtureRule(); // may pass a custom enhancedRandom instance here

    @RandomFixture
    private Person person;

    @RandomFixture
    private int[] ints;

    @org.junit.Test
    public void testSortAlgo() throws Exception {
        int[] sortedInts = myAwesomeSortAlgo.sort(ints);

        assertThat(sortedInts).isSorted(); // fake assertion
    }

    @org.junit.Test
    public void testPersistPerson() throws Exception {
        personDao.persist(person);

        assertThat("person_table").column("name").value().isEqualTo(person.getName()); // assretj db
    }

}
```

This can also be done using a junit runner (and probably it is a better option):

```java
@RunWith(RandomFixtureJUnitRunner.class)
public class Test {

    @RandomFixture
    private Person person;

    @RandomFixture
    private int[] ints;

    @org.junit.Test
    public void testSortAlgo() throws Exception {
        int[] sortedInts = myAwesomeSortAlgo.sort(ints);

        assertThat(sortedInts).isSorted(); // fake assertion
    }

    @org.junit.Test
    public void testPersistPerson() throws Exception {
        personDao.persist(person);

        assertThat("person_table").column("name").value().isEqualTo(person.getName()); // assretj db
    }

}
```

@PascalSchumacher What do you think? I believe this will tremendously simplify the hassle of generating test fixtures for junit users (I'm not sure testng has the same mechanism of rules).

**Comment by benas** [comment]
In hindsight, this has no real added value compared to good old junit setup method.
moreover, this makes me look for the "given" clause somewhere outside my test (in the state of the test class). I think this is better:

```java
    @org.junit.Test
    public void testPersistPerson() throws Exception {
       // given
       Person person = random(Person.class);

       // when
        personDao.persist(person);

       // then
        assertThat("person_table").column("name").value().isEqualTo(person.getName()); // assretj db
    }
```

The burden of adding a new annotation and a junit runner and the code to make it work is not worth the (small) added value of this feature.

**Comment by benas** [comment]
BTW, these two examples (persisting a domain object and sorting a set of numbers) can be added to the readme as showcases of how random beans can be useful in tests (where the test fixture is not important to the test logic)

**Comment by PascalSchumacher** [comment]
I would have preferred the rule anyway, as runners are not composeable and there are already a lot of important runners out there (parameterized, junitdataprovider, theories, spring...).

Sorry for the late feedback (was on vacation).

**Comment by benas** [comment]
It's always better to have the AAA close to each others. Here with this new feature, the 'arrange' will be spread accross the test class state and will have to be coherent with test methods lifecycle (Should it be shared? recreated for each method? and so on).

> In hindsight, this has no real added value compared to good old junit setup method.

I'm closing this issue.

@PascalSchumacher Thank you for your feedback
