### ISSUE TITLE
Randomizer for Long.class on primitive long field, not picked up. 

### ISSUE THREAD

**Issue by dzonekl** [benas/random-beans#255]
Hey there, thanks for this library :-) 
A bean we try to populate, has a primitive long field, which fails to match the field definition, 
for the randomizer. Perhaps an oversight on how to use the API, but here is what I am trying: ``

`static FieldDefinition<?, ?> priceInCents = field().named("priceInCents").ofType(Long.class).inClass(SomeClass.class).get();
`
I debug, the `AbstractRandomizerRegistry` method `hasType` which fails to match type **long** with type **Long**.  

I managed to make it work with `long.class` in the definition. As I spend a bit of time, debugging, perhaps something worth to document on the excellent wiki. 

Thank you. 
CHristophe

**Comment by PascalSchumacher** [comment]
Hi dzonekl,

thanks for reporting. :+1: 

Are you using random-beans 3.6.0? Starting with 3.6.0 randomizers should also be used for the matching primitive type, see https://github.com/benas/random-beans/commit/75318b09cb2cb6445b360713966d9d63d10e8990 for details.

**Comment by dzonekl** [comment]
Yes, 3.6.0

**Comment by benas** [comment]
Hi @dzonekl 

Thank you for reporting this. I'm trying to reproduce the issue using v3.6.0 with the following test case:

```java
import io.github.benas.randombeans.randomizers.number.LongRandomizer;
import org.assertj.core.api.Assertions;
import org.junit.Test;

import static io.github.benas.randombeans.FieldDefinitionBuilder.field;

public class TestIssue255 {

    @Test
    public void test() throws Exception {
        FieldDefinition<?, ?> priceInCents = field().named("priceInCents").ofType(Long.class).inClass(Product.class).get();

        Product product = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
                .randomize(priceInCents, new LongRandomizer())
                .build()
                .nextObject(Product.class);

        Assertions.assertThat(product).isNotNull();
        Assertions.assertThat(product.getPriceInCents()).isNotNull();
    }

    class Product {

        private long priceInCents;

        public Product(long priceInCents) {
            this.priceInCents = priceInCents;
        }

        public long getPriceInCents() {
            return priceInCents;
        }

        public void setPriceInCents(long priceInCents) {
            this.priceInCents = priceInCents;
        }
    }
}
```

The test is passing, I'm not able to reproduce the issue.
Is this what you are trying to do?

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @dzonekl 

Any updates on this issue? Can you provide a failing unit test with v3.6.0 ?

Kr
Mahmoud

**Comment by dzonekl** [comment]
Hi Mahmoud, 
your test looks what I initially tried, which failed to work. 
As I wrote, now I use: 

`static FieldDefinition<?, ?> priceInCents = field().named("priceInCents").ofType(long.class).inClass(Some.class).get();
`
when Some.class is a class with a field priceInCents of type 'long' and works fine.  

So I am puzzled why you don't get the error I (was) seeing. 
I will close it.
