### ISSUE TITLE
Broken code in the wiki

### ISSUE THREAD

**Issue by berezovskyi** [benas/random-beans#256]
```
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
       .randomize(FieldDefinitionBuilder.field().named("accounts").ofType(Set.class).inClass(Transaction.class), new SetRandomizer<Account>(accountRandomizer))
.build();
```

in https://github.com/benas/random-beans/wiki/Supported-types#3-arrays-and-collection-types should have `.inClass(Transaction.class).get()` method call to build properly.

**Comment by benas** [comment]
Oh sorry for that. Thank you for reporting this!

I've updated the page with the correct snippet.

Kr
Mahmoud
