### ISSUE TITLE
Enhancement: Add a kotlin library

### ISSUE THREAD

**Issue by jpopadak** [benas/random-beans#262]
* If you are requesting a feature, don't hesitate to explain in detail your suggestion with code examples.
If I have the following Kotlin data class, I would like random beans to automatically pick up on the fact that it is a kotlin class knowing it is non null.

I have to write all my random lines like so: 
 `val store = random(Store::class.java)!!`

Instead of:
 `val store = random(Store::class)`

Yes, this is a small particular, but it would make code cleaner to view along with knowing what is and is not required for classes / data classes.

**Comment by benas** [comment]
Hi,

I don't know much about kotlin (yet), so please correct me if I'm wrong.

> I would like random beans to automatically pick up on the fact that it is a kotlin class

Is this possible? random beans acts at runtime, so I'm not sure how it can know at compile time if it is a Java class or a Kotlin class.

The syntax sugar you are suggesting is definetly a good one, but IMO, it is only possible by porting random beans to kotlin. Do you agree?

Kr
Mahmoud

**Comment by magx2** [comment]
AFAIK you need to create new project - ```random-beans-kotlin``` - with some overloaded methods.

**Comment by benas** [comment]
I think this feature is very interesting, but better provided by a separate kotlin library than a kotlin module in random beans (and mix java/koltin in the same code base).

If this library is developed, I would love to add a reference to it in the readme.

I'm closing this issue for now. Thank you for your suggestion,
