### ISSUE TITLE
[feature request] api of getting random bean from object pool

### ISSUE THREAD

**Issue by vipcxj** [benas/random-beans#263]
I need a api to getting the random bean from object pool by type. Or does it exist already?

**Comment by benas** [comment]
Hi,

There is an internal object pool used by random beans but it is not exposed through an API.

What you can do is create random objects using random beans and use a pooling library to get a random object from the pool.

Does this helps?

Kr
Mahmoud

**Comment by vipcxj** [comment]
I can put the direct random objects to a pool myself, but it is difficult to put the nest random beans to a pool.

**Comment by benas** [comment]
You can pool nested objects with a separate `EnhancedRandom` instance then link them to root objects (which might be pooled separately). So I see no added value in exposing an internal state of an `EnhancedRandom` instance.

I'm closing this issue. Thank you for your suggestion.
