### ISSUE TITLE
Email randomizer should not generate email addresses with valid domains.

### ISSUE THREAD

**Issue by chintebay** [benas/random-beans#265]
I feel generating a real valid email address can led to actual issue some day (chance !)...maybe this should be generated with invalid email domains like h0tma1l.com or some such.

Apart from that, this looks great ! 

Best,
C

**Comment by PascalSchumacher** [comment]
Random-beans uses https://github.com/DiUS/java-faker to generate email addresses.

If you want more control over the generated email addresses you can use java-faker directly. For example `new Faker().internet().safeEmailAddress()` should generate a email address without a valid domain.

**Comment by benas** [comment]
Another option is to create a custom email randomizer that delegates domain name creation to a StringRandomizer. This will generate random domain names

**Comment by benas** [comment]
Another possibility is to add a parameter `safe` to the current `EmailRandomizer` to generate safe emails (delegating to faker's `safeEmailAddress` method).

@PascalSchumacher @chintebay What do you think?

**Comment by PascalSchumacher** [comment]
>@PascalSchumacher @chintebay What do you think?

Sounds good imho.

**Comment by benas** [comment]
Hi @chintebay 

Version 3.8.0-SNAPSHOT adds a boolean parameter called `safe` in the `EmailRandomizer` to generate safe emails (with invalid domain names).

Can you give it a try?

Kr
Mahmoud
