### ISSUE TITLE
Setting number range for a specific  field in a bean

### ISSUE THREAD

**Issue by kakurala** [benas/random-beans#267]
It is good to have a field level control on randomization, like strings & dates.

For ex. if Person bean has a age field then it should contain numbers between 1-100 but the code in attached screenshot always generates some random 4-5 digit number.

![image](https://user-images.githubusercontent.com/13654935/29777088-6caf2396-8c28-11e7-8625-ac52c113e63d.png)

**Comment by kakurala** [comment]
Sorry, With field level custom randomizer am able to set a boundary to age field.
		EnhancedRandom random = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
				.randomize(field().named("age").ofType(Integer.class).inClass(Person.class).get(), new Randomizer<Object>(){

					@Override
					public Object getRandomValue() {
						Integer s = (new Random()).nextInt(100);
						
						return s;
					}
					
				})
				.stringLengthRange(5, 35)
				.build();

**Comment by benas** [comment]
@kakurala Indeed, you can register a custom randomizer for a specific field as you did.

Great! you found it ;-)
