### ISSUE TITLE
Spring Boot support?

### ISSUE THREAD

**Issue by steventong** [benas/random-beans#271]
Hi, @benas 

Your project is very helpful to write unit test. My project is based on Spring Boot, I want to generate my test POJO with custom randomizer.  But I don't know how to do it?

**Comment by benas** [comment]
Hello @steventong 

Thank you! I'm glad you find random beans helpful.

>  I want to generate my test POJO with custom randomizer

You can implement the `Randomizer` interface and use your custom randomizer.
More details about this in the wiki [here](https://github.com/benas/random-beans/wiki/Key-APIs#the-randomizer-interface).

In regards to your question about Spring Boot, random beans provides `EnhancedRandomFactoryBean` to be used in a spring context. You can find how to use it [here](https://github.com/benas/random-beans/wiki/spring-support).

Does this helps?

Kr
Mahmoud

**Comment by steventong** [comment]
Got it. Thanks for your reply.
