### ISSUE TITLE
do we have an equality check method for random generated beans?

### ISSUE THREAD

**Issue by fyh** [benas/random-beans#272]
hi, today I was writing some unit tests and found random-beans, I think it's cool and make my life so much easier. I can generate random beans for test data-preparation which have a lot of fields. 
for example:
```java
    @Autowired
    private PersonDao dao;

    @Test
    public void saveTest() {
        Person person = enhancedRandom.nextObject(Person.class);
        dao.insertSelective(person);
        Person personEntity = dao.selectByPrimaryKey(person.getId());
        // test whether person has the same fields as personEntity
    }
```

The problem is I don't know how to easily check fileds equality between generated bean and the selected entity bean using DAO.
So, Is there an equality check method for random generated beans? 

Thanks!

**Comment by benas** [comment]
Hi,

Thank you, I'm glad you find random beans useful!

If you are using assertj, you can use the `isEqualsToByComparingFields` method. For example:

```java
Assertions.assertThat(person).isEqualsToByComparingFields(personEntity);
```

This will compare all fields for you. Does this help?

Kr
Mahmoud

**Comment by fyh** [comment]
Hi,

Thanks. `isEqualsToByComparingFields` really does what I want. The cost is to import another library.
I suppose I shoud reinvent some code for equality check only, maybe an another `Utils.java`, which can be small and handful.

**Comment by PascalSchumacher** [comment]
AssertJ has really nice DSL (https://joel-costigliola.github.io/assertj/), great support for specific assertions on JDK types (String, Iterable, Streams, etc.) and very helpful error messages.

It also has not dependencies, so it's only single additional dependency.

You should give it try. It's the best java assertion library imho.

**Comment by benas** [comment]
> I shoud reinvent some code

Don't reinvent the wheel 😄 Seriously, use assertj, it's super awesome.
