### ISSUE TITLE
Restrict range on numeric values

### ISSUE THREAD

**Issue by VSZM** [benas/random-beans#276]
The builder has some neat methods already for restricting Time, Date and String ranges.

I just ran into an issue where the database only accepts numbers within a certain range. Since my POJO has dozens of fields it is not feasable to set them each. I should be able to specify a range for double and int values in the _EnhancedRandomBuilder_.

**Comment by benas** [comment]
Hi,

Have you tried to use one of the [range randomizers](https://github.com/benas/random-beans/tree/master/random-beans/src/main/java/io/github/benas/randombeans/randomizers/range) ? Something like:

```java
EnhancedRandom enhancedRandom = aNewEnhancedRandomBuilder()
                .randomize(Double.class, new DoubleRangeRandomizer(1, 10))
                .build()
```

Does this help?

Kr
Mahmoud

**Comment by VSZM** [comment]
Will this work also if the field is a primitive type?

**Comment by benas** [comment]
Yes, it should work fine.

You can also be more precise when specifying the type. Here is an example: https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/randomizers/range/IntegerRangeRandomizerTest.java#L86

**Comment by VSZM** [comment]
Thanks, this is great!

The only suggestion I have remaining is to include this feature in the README.md for future users :)

Keep up the awesome work!
