### ISSUE TITLE
Add support for Bean Validation 2.0

### ISSUE THREAD

**Issue by magx2** [benas/random-beans#277]
Could you update validation dependency to ```2.0.0.final``` https://mvnrepository.com/artifact/javax.validation/validation-api/2.0.0.Final?

Also can you add support for ```javax.validation.constraints.Positive``` annotation?

**Comment by benas** [comment]
Yeah good idea!

Do you want to help? You are welcome to contribute to the project!

**Comment by benas** [comment]
Any update on this?

> Also can you add support for javax.validation.constraints.Positive annotation?

Please open a separate issue for this request.

**Comment by benas** [comment]
> Also can you add support for javax.validation.constraints.Positive annotation?

@magx2  This has been added in the latest 3.0.8-SNAPSHOT version. Can you give it a try? (if you don't know how to use import the snapshot version, see [here](https://github.com/benas/random-beans/wiki/Getting-Started#maven-usage)).

Currently, I have:

- [x] Updated the dependency to bean validation to 2.0
- [x] Added support for `@Positive` annotation (see 82541ea087487bde0d38497c5e943cae1eb17f99)

What is planned for 3.8:

- [ ] Add support for `@PositiveOrZero`
- [ ] Add support for `@Negative`
- [ ] Add support for `@NegativeOrZero`
- [ ] Add support for `@NotBlank`
- [ ] Add support for `@NotEmpty`
- [ ] Add support for `@Email`

We can leverage existant randomizers to implement these annotations.

You are welcome to contribute if you want!

**Comment by magx2** [comment]
Looks OK for me

**Comment by benas** [comment]
I finished adding support for planned annotations for v3.8. Those can be already tested with the latest snapshot version.
