### ISSUE TITLE
[Feature request] generate random-beans-testbeans lib and upload to maven repository

### ISSUE THREAD

**Issue by jiming** [benas/random-beans#281]
Because writing unit test require some test beans. Each time writing a new bean is really a waste of time. The beans your defined (Address, Bar, Human, Mamals...) for unit test is quite good as a lib for this purpose.

What about package them and upload to maven repository as well. Or simple move the test beans from `test` directory to `main` directory

Have a nice day!

**Comment by benas** [comment]
Hi,

Are you planning to use these beans is a separate project than random beans?
I don't see any added value to publish this artifact to maven central. Those are specific beans created to test random beans behaviour.

You can still copy them for free! No credit card required 😄 

Kr
Mahmoud

**Comment by jiming** [comment]
Hi Mahmoud,

Yes, I wanted to use the beans in my unit test code. Of course, not in product environment.

Some time when write a unit test, especially not business related code, I need define some POJO. Most time they can be any simple POJO, but I have to define them again and again. Which is a pain in the neck.

For example, I need test Collectors.toMap from jdk8

```
    @Test
    public void test_toMap_withMerge() {

        AtomicInteger counter = new AtomicInteger(1);
        Stream<FakeName> objects = enhancedRandom.objects(FakeName.class, 4);
        List<FakeName> fakeNames = objects.map(f -> {
            f.setId(counter.getAndIncrement() % 3);
            f.setFirst(String.valueOf(counter.get()));
            return f;
        }).collect(Collectors.toList());
        fakeNames.forEach(f -> System.out.println(">" + f.getId() + ":" + f.getFirst()));
        Map<Integer, String> maps1 = fakeNames.stream().collect(Collectors.toMap(FakeName::getId, FakeName::getFirst, (s, s2) -> s));
//        Map<Integer, String> maps = fakeNames.stream().collect(Collectors.toMap(FakeName::getId, FakeName::getFirst));
//        List<FakeName> fakeNames = EnhancedRandom.randomListOf(3, FakeName.class);
        System.out.println(maps1);

        int[] a = {1, 2};
        System.out.println(IntStream.of(a).average().toString());

    }
```

Thanks!
