### ISSUE TITLE
Junit5 module for random parameters

### ISSUE THREAD

**Issue by reitzmichnicht** [benas/random-beans#284]
Hi

Is there any interest in a junit5 extension allowing this backed by random-beans:

```
@ExtendWith(RandomExtension.class)
class RandomExtensionTest {

  @Test
  void randomString(@Random String s) {
    assertThat(s).isNotEmpty();
  }

    @Test
    void randomList(@Random(size = 1) List<String> list) {
      assertThat(list).hasSize(1);
    }
}
```

If yes I would create another pull request with an extra module.

Kind regards,
Michael

**Comment by glytching** [comment]
FWIW, https://github.com/glytching/junit-extensions (docs: https://glytching.github.io/junit-extensions/randomBeans)

**Comment by reitzmichnicht** [comment]
Great to see there is a place for junit5 extensions I wasn't aware of.
My RandomBeans extension is more advanced, if benas doesn't want to include it as module I will sent a pull request to your project.

**Comment by benas** [comment]
@reitzmichnicht 

Thank you for this suggestion! I remember having a similar idea of a junit extension in #251, but it is not the same. Now with the new and elegant junit5 extension API, I think it is worth adding this feature.

> My RandomBeans extension is more advanced, if benas doesn't want to include it as module I will sent a pull request to your project.

I don't have any objection to add a module for such an extension, but I think you can suggest your more advanced features to the extension of @glytching . The idea is not to end up with two extensions (the one you will add to random beans and the current one from @glytching ). What do you think?

@glytching Your extension is fantastic! thank you very much 👍 
May I add a reference to it in the readme?

**Comment by glytching** [comment]
@benas 

> @glytching Your extension is fantastic! thank you very much

Seems to me that you have done the hard work, all I did was put some JUnit sugar on top of it :)
 
> May I add a reference to it in the readme?

Of course

**Comment by glytching** [comment]
@reitzmichnicht 

> My RandomBeans extension is more advanced, if benas doesn't want to include it as module I will sent a pull request to your project.

Sounds good, I'd be happy to see the extension, erm, extended :)

**Comment by benas** [comment]
> May I add a reference to it in the readme?
> Of course

Done here : 0a1af26f3f18677b65a74eaceebe6b0e5a78ed25 Thank you @glytching !

> Sounds good, I'd be happy to see the extension, erm, extended :)

@reitzmichnicht I let you suggest your improvements to the existing extension if you want.
I'm closing this issue for now.
