### ISSUE TITLE
Missing API to retrieve seed value

### ISSUE THREAD

**Issue by reitzmichnicht** [benas/random-beans#286]
Hi

To document the generated seed of EnhancedRandom in unit tests it would be great to have an API to get the value without reflection. This is essential to reproduce test failures.
My suggestion would be to enhance the EnhancedRandom interface with a getParameters() method which will return a read only implementation of EnhancedRandomParameters.
I can create a pull request for it.

Kind regards,
Michael

**Comment by benas** [comment]
Hi,

`EnhancedRandomParameters` should not have been made public. This is a design mistake in random beans IMO. This class is not used in any public APIs.

Normally, `EnhancedRandomParameters` should become public when `RandomizationContext` will become public (as part of the randomization context, see #6 ).

That said, when you create an `EnhancedRandom` instance with some parameters, you know which parameters you created the instance with. Why would you need to get access them from the instance? To make an analogy with `java.util.Random`, there is no getter for the seed. When I create a `Random` with a seed, I know the seed I used so there is no point to get it from the instance. Does this make sense?

Kr
Mahmoud

**Comment by benas** [comment]
I'm closing this issue. I see no added value to have a getter for the seed. And I must admit making `EnhancedRandomParameters` public is a mistake.
