### ISSUE TITLE
Mockito like API

### ISSUE THREAD

**Issue by Toilal** [benas/random-beans#29]
It would be awesome to have some kind of [Mockito](http://mockito.org/)-like API to register randomizer using reflection. It involves some hacking with [cglib](https://github.com/cglib/cglib), but it's possible to implement this kind of magic ...

```java

import static io.github.benas.jpopulator.api.reflect.*

public static class BeanA {
    private String label;
    private int id;

    // getters/setters are defined ...
}

...
BeanA a = jpopulator(BeanA.class)

randomizer(a.getLabel(), new Randomizer() { 
    // The randomizer ...
});
// instead of PopulatorBuilder.registerRandomizer(BeanA.class, String.class, "label", ...);

ignore(a.getId()); // Ignore this field

BeanA populatedBean = populate(a); // Generate a single bean
List<BeanA> populatedList = populate(a, 100); // Generate a list of 100 beans

```

This API would make jPopulator based tests really easier to maintain on bean changes, because there are no hardcoded classes and property names in randomizer registrations.

**Comment by benas** [comment]
This is a nice to have feature. A Mockito-like API has been also suggested [here](https://github.com/benas/jPopulator/issues/9#issuecomment-62683160) but as you said, it requires some black magic and a big refactoring of the code base. Let's keep this feature request in the pipe. Contributions are welcome!

**Comment by Toilal** [comment]
I'm not sure it requires refactoring, I think this "black magic" API could delegate to the existing API.

There are some explanations on how Mockito `when()` on [stackoverflow](http://stackoverflow.com/questions/14440270/how-does-mockito-when-invocation-work). For me, It's still quite confuse on how to implement this cleanly though, but i'll give it a try next week.

**Comment by PascalSchumacher** [comment]
For a quick and very unfinished prototype see: https://github.com/benas/random-beans/pull/98

**Comment by benas** [comment]
Hi All,

I need some time to analyze in depth the relevance and effort needed for this PR.
Hence, I'm postponing it to v3.1

Kind regards
Mahmoud

**Comment by punkratz312** [comment]
+1

**Comment by benas** [comment]
Even though the requested feature is a good idea, I think the added value of the syntactic sugar is not worth it in comparison with the effort needed to implement it. I'm closing this issue for now.
