### ISSUE TITLE
Data population not working for List<List<Integer>>

### ISSUE THREAD

**Issue by premik91** [benas/random-beans#290]
Hi, I tried populating my POJOs and it works great. The problem comes if my POJO has nested lists ( List<List<Integer>>), these fields are not populated. Am I doing something wrong or is this some kind of feature? ;)

**Comment by benas** [comment]
I'm not sure random beans is able to populate nested structures. You can still write a custom randomizer for the field of this type (ListRandomizer may help in this case).

Does this helps?
