### ISSUE TITLE
Generation of value for field B depends on value of field A

### ISSUE THREAD

**Issue by slavomir-ziak** [benas/random-beans#291]
Hi there!

My class:

```
class Person {
PersonType type;
String id;
}
enom PersonType {PRIVATE, PUBLIC}
```

value of person.id field is different for persons of type PRIVATE and different for persons of type PUBLIC.
is it possible to write a Randomizer that takes parameters, so i can generate different values od id based on type?

thanks

**Comment by PascalSchumacher** [comment]
Hi,

you can implement a custom randomizer e.g.

```java
Randomizer<Person> personRandomizer = new Randomizer<Person>() {

    @Override
    public Person getRandomValue() {
        // logic to create random Person
    }
};
```

And register it by using "direct" registration:

``` java
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
        .randomize(Person.class, personRandomizer).build();
```

or register it using a custom randomizer registry, see: https://github.com/benas/random-beans/wiki/Grouping-Randomizers

Hope this helps,
Pascal

**Comment by benas** [comment]
@slavomir-ziak Any update on this?

If Pascal's comment answers your question, please close this issue.

**Comment by slavomir-ziak** [comment]
Yeah that should do it. I didnt have to use it in the end, but looks good to me.
Thanks for your help Pascal.
