### ISSUE TITLE
Validation + some RegEx cause very slow generation

### ISSUE THREAD

**Issue by TheJavaGuy** [benas/random-beans#292]
Hello guys,

I noticed a case where generation of beans is very slow (almost a minute for one bean). That happens when beans use validation + regex, like this: `@Pattern(regexp = "(.{1,6})( *, *(.{1,6})){0,15}")` I use random-beans 3.7.0 and Hibernate validator 6.0.7.

I attached a minimal gradle/IntelliJ project which demonstrates the issue.
[RandomBeansRegExIssue.zip](https://github.com/benas/random-beans/files/1703395/RandomBeansRegExIssue.zip)

Now I am perfectly aware that people can create all sorts of nasty regexes and that's probably impossible to quickly generate a string which satifies them. Yet I hope that it's possible to speed up generation for some cases.

If you need any more info, help or whatever please contact me. Thank you!

**Comment by PascalSchumacher** [comment]
Hi Ivan,

thanks for reporting this. RandomBeans uses https://github.com/DiUS/java-faker which uses https://github.com/mifmif/Generex to generated data based on regular expressions.

Therefore this issue should be reported at https://github.com/mifmif/Generex

Thanks!

**Comment by TheJavaGuy** [comment]
@PascalSchumacher Thank you for the answer! After a bit more research I found the Generex and opened an issue there. I'll close this now.

**Comment by ghilainm** [comment]
Seems like the project you depends on is dead. Would you maybe consider, moving to another one for generating regepx? Because it is unusable in the current state with such slow generation. On my side it simply never reach the end.

**Comment by benas** [comment]
> Seems like the project you depends on is dead. Would you maybe consider, moving to another one for generating regepx?

Definitely yes, do you know any good alternative?

**Comment by ghilainm** [comment]
Unfortunately no! If I come across that I keep you informed.
