### ISSUE TITLE
Support for null values

### ISSUE THREAD

**Issue by tempuser14** [benas/random-beans#296]
Are there any possibilities to leave randomly some fields with their default values or to set also null field values with a certain probabiliy?

Many thanks upfront!

**Comment by benas** [comment]
> leave randomly some fields with their default values

The [`overrideDefaultInitialization `](https://github.com/benas/random-beans/wiki/Randomization-parameters#override-default-initialization) parameter is used for this use case. It is false by default, so random beans does will override default values.

> set also null field values with a certain probabiliy?

The [OptionalRandomizer](https://github.com/benas/random-beans/blob/master/random-beans/src/main/java/io/github/benas/randombeans/randomizers/misc/OptionalRandomizer.java) is the closest to what you are looking for.

Hope this helps.
