### ISSUE TITLE
String length for specific field

### ISSUE THREAD

**Issue by vladamx** [benas/random-beans#298]
Is this possible?
Examples document only global length configuration.

**Comment by benas** [comment]
You can specify a randomizer for a specific field like this:

```java
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
.stringLengthRange(1,50)
.randomize(FieldDefinitionBuilder.field().named("name").ofType(String.class).inClass(Person.class).get(), new StringRandomizer(10))
   .build();
```

In this example, fields of type String will be randomized with values having up to 50 characters, while the `name` field in `Person` type will be set to a random String of a maximum of 10 characters.

You can find more details in the [wiki](https://github.com/benas/random-beans/wiki/Key-APIs#or-programmatically-by-registering-the-randomizer-like-this).
