### ISSUE TITLE
Uncorrect behavior overrideDefaultInitialization parameter in Kotlin

### ISSUE THREAD

**Issue by glockbender** [benas/random-beans#304]
Entity i used:
```
@Entity
@Table(name = "deposits")
data class Deposit(

        @Column(name = "name", nullable = false)
        var name: String,

        @Column(name = "description")
        var description: String? = null,

        @OneToMany(cascade = [CascadeType.ALL], fetch = FetchType.LAZY)
        @JoinColumn(name = "deposit_id")
        // AS YOU SEE I'M INITIALIZE THIS LIST
        val members: MutableList<DepositMember> = mutableListOf()

) : AbstractIdVerTimed()
```
overrideDefaultInitialization as default is false, but after `use random(Deposit::class)` list initialize and populates DepositMember
![bug](https://user-images.githubusercontent.com/16047417/40391584-70b97f42-5e21-11e8-92cc-0d0f35b21112.png)

**Comment by glockbender** [comment]
As i understand from library sources, need add a new instantination strategy for Kotlin. Because there is initialized properties in constructor with special marker

**Comment by benas** [comment]
Yeah, I think there are some adjustments to make RB work with Kotlin (See also #262). So I'm not sure RB as it is today (designed to generate Java beans) should be modified to support Kotlin Data classes. This can be done in another library that ports RB to kotlin.

@glockbender Do you agree?
