### ISSUE TITLE
How to generate a random Collection with Generics. Example: List<Pojo>

### ISSUE THREAD

**Issue by stevensouza** [benas/random-beans#311]
Is there a  direct way of doing this.  Something like the following (it isn't valid syntax):
```java
EnhancedRandom randomGenerator = EnhancedRandomBuilder.aNewEnhancedRandomBuilder().build();
List<Pojo> list = randomGenerator.nextObject(List<Pojo>.class);

```

When the list is in another class it works though, but the above would be more straightforward.

```java
EnhancedRandom randomGenerator = EnhancedRandomBuilder.aNewEnhancedRandomBuilder().build();
PojoList pojoList = randomGenerator.nextObject(PojoList.class);
List<Pojo1> randomList = pojoList.list;
```
Here are the classes referenced above....

```java
   static class Pojo {
        private String firstName;
    }

   static  class PojoList  {
        List<Pojo1> list;
    }

```

**Comment by PascalSchumacher** [comment]
Hi Steven,

sadly there is no way. Because of type erasure generic information is not available at runtime in Java. E.g you can not determine the generic type of a `List` passed as a method argument.

Random beans can generate the list in `PojoList` because generic information is available for fields.

**Comment by stevensouza** [comment]
ModelMapper allows for it to be done, so I would think it is possible.  ModelMapper is similar, but instead of returning random data it copies data from one Pojo to another type of Pojo. For example copying entity data to a ValueObject.

```java
List<Pojo2> pojo2List=populate();
TypeToken typeToken = new TypeToken<List<Pojo1>>(){};
List<Pojo1> list = new ModelMapper().map(pojo2List, typeToken.getType())
```
This is almost the same situation, so I would think at a minimum a syntax like this should work for random beans too.

**Comment by stevensouza** [comment]
Here is an example from their documentation.  Note the TypeToken class is a google guava class.

http://modelmapper.org/user-manual/generics/

**Comment by stevensouza** [comment]
Thanks for the api by the way.  I am using it to generate test data in a  complex class structure that would be difficult to create in any other way.

**Comment by stevensouza** [comment]
Well, a current method you have will take care of most of my cases.

>         List<Person> persons = randomListOf(SIZE, Person.class);

**Comment by benas** [comment]
> Well, a current method you have will take care of most of my cases.

Indeed, when I first saw this:

```java
EnhancedRandom randomGenerator = EnhancedRandomBuilder.aNewEnhancedRandomBuilder().build();
List<Pojo> list = randomGenerator.nextObject(List<Pojo>.class);
```

I was about to suggest `List<Pojo> pojos = randomListOf(SIZE, Pojo.class);`

I think this is the way to go for now in order to keep it simple instead of fighting type erasure and introducing more complexity in the code base with something equivalent to `TypeToken`.

@stevensouza Do you agree?

**Comment by benas** [comment]
I'm closing this issue for now as we have a solution (`List<Pojo> pojos = randomListOf(SIZE, Pojo.class);`) without the need to introduce more complexity in the code base with something equivalent to `TypeToken`.

@stevensouza You can always add a comment here if you want.

**Comment by stevensouza** [comment]
Sorry, I just saw your question.  Yes, I think the methods randomListOf, randomSetOf, and randomStreamOf would cover most use cases.  You can keep this closed.  

Thanks again for the nice api and the time you put into the project!
Steve

**Comment by PascalSchumacher** [comment]
> I can't find this method (randomListOf()). Could you show class and denpendency which contain this method randomListOf ? Thanks!

I believe these methods were removed in a recent major version.

**Comment by yuhangbin** [comment]
> > I can't find this method (randomListOf()). Could you show class and denpendency which contain this method randomListOf ? Thanks!
> 
> I believe these methods were removed in a recent major version.
Thank you.

**Comment by yuhangbin** [comment]
This project support to generate ParameterizedType class ?  If it can, where have examples?

**Comment by armandino** [comment]
@stevensouza if you still need support for creating arbitrary generic types, please check out

https://github.com/instancio/instancio

It supports specifying generic types using `TypeToken`s.
