### ISSUE TITLE
Collection attribute is only set when it is null

### ISSUE THREAD

**Issue by tnmtechnologies** [benas/random-beans#314]
Hello,

First of all thank you for the very usefull library.

My problem is about the initialization of an attribute of type List which is initialized by default to an empty list in the bean itself.

I applied the description available in this page [https://github.com/benas/random-beans/wiki/Supported-types](https://github.com/benas/random-beans/wiki/Supported-types). I tested my code and I found that the the list of the given attribute was always empty.

Then after some investigation, I found in the random-beans code that an attribute of type collection is only set if it is null.
It explains why it doesn't work in my case.

Would it be possible to take into account this use case?
I don't have the hand on the bean I want to randomize.

A proposal could be to add a method to the class FieldDefinitionBuilder like whenNotNull() or something similar. It would improve the current behaviour.

To reproduce the problem from the example in page  [https://github.com/benas/random-beans/wiki/Supported-types](https://github.com/benas/random-beans/wiki/Supported-types) , we just need to initialize the accounts attribute in the class Transaction 

```
public class Transaction {
   private Set<Account> accounts = new HashSet();
}

```

Thank you.

**Comment by benas** [comment]
Have you tried to set the [`overrideDefaultInitialization`](https://github.com/benas/random-beans/wiki/Randomization-parameters#override-default-initialization) parameter?

**Comment by tnmtechnologies** [comment]
Sorry , I missed it. It now works fine.

Thank you.
