### ISSUE TITLE
Nondeterministic randomizer selected in CustomRandomizerRegistry for conflicting field definitions

### ISSUE THREAD

**Issue by aewhite** [benas/random-beans#317]
`CustomRandomizerRegistry` currently iterates over the key set of its `customFieldRandomizersRegistry` and selects the first matching field definition that it finds. If multiple field definitions apply then which is chosen is nondeterministic. 

It would be nice if either:

1. Order mattered - the first/last randomizer registered wins 
2. Specification mattered - the most specific randomizer wins

**Why this matters**

It's nice to specify a default property for a common field name (for example "ip") but then also be able to say "for the ip field in this one class, use this pool of ips instead". 

**The workaround**

I'm going to create a higher priority registry that uses option (1) above.

**Comment by benas** [comment]
Any update on this? an example would be really helpful to understand the use case.

**Comment by benas** [comment]
@aewhite Please re-open this issue when you manage to provide an example that explains the use case.

Thank you.

**Comment by aewhite** [comment]
For some reason, the comments here never made it back to my email. 

I don't have much to add over my original comment. The example given is almost exactly the use case. Maybe I can address your confusion about why you might have multiple field definitions. That need arises naturally when you have a general rule and a specific rule. If you have the same class type being used in N places in your object graph, then it's nice to say that "in general property P in class C is X, but if C is being used in class D then P should being something else".
