### ISSUE TITLE
Past/Future annotation cannot be applied to java8 date types

### ISSUE THREAD

**Issue by neetkee** [benas/random-beans#328]
If we will put Past annotation on java 8 date type:

```java
@Past
private LocalDate localBirthDay;
```
we will get the exception:
```java
Caused by: java.lang.IllegalArgumentException: Can not set java.time.LocalDate field io.github.benas.randombeans.validation.BeanValidationAnnotatedBean.localBirthDay to java.util.Date
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at io.github.benas.randombeans.util.ReflectionUtils.setProperty(ReflectionUtils.java:96)
	at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:88)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateField(EnhancedRandomImpl.java:158)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateFields(EnhancedRandomImpl.java:149)
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:120)
	... 41 more
```

The problem is in [PastAnnotationHandler]( https://github.com/benas/random-beans/blob/master/random-beans-validation/src/main/java/io/github/benas/randombeans/validation/PastAnnotationHandler.java), I guess. It returns DateRangeRandomizer without respecting the type. Should we check for type in this class, something like this?
```java
 if (field.getType().equals(LocalDate.class)) {
            LocalDate now = LocalDate.now();
            return new LocalDateRangeRandomizer(now.minusYears(Constants.DEFAULT_DATE_RANGE), now.minusDays(1));
 }
```
Or there is a better way to do this?

**Comment by PascalSchumacher** [comment]
Another option to solve this could be to use https://github.com/benas/random-beans/blob/master/random-beans/src/main/java/io/github/benas/randombeans/randomizers/registry/TimeRandomizerRegistry.java to look up the Java 8 date type.

**Comment by benas** [comment]
It is not possible to "combine" criteria of two randomizer registries today. In the given example, these two criteria are "Custom date type" (coming from `TimeRandomizerRegistry`) and "In the past" (coming from `BeanValidationRandomizerRegistry`). It is possible to order registries with the `@Priority` annotation, and we end up with one randomizer picked up for the field (BTW @PascalSchumacher I tried to add `TimeRandomizerRegistry` but didn't help) but it is not possible to combine them.

> Should we check for type in this class, something like this?

I won't do it that way because we will need to check [all types](https://docs.jboss.org/hibernate/stable/beanvalidation/api/javax/validation/constraints/Past.html) supported by the annotation] with multiple if/then statement.

I'm not sure (yet) if this is a design "bug" or a feature request, so I planned it for the next major version v4 to take some time and think how to correctly tackle the case.

In the meantime, it is always possible to use a custom randomizer for the field and leverage the `LocalDateRangeRandomizer`, something like:

```java
import io.github.benas.randombeans.EnhancedRandomBuilder;
import io.github.benas.randombeans.FieldDefinitionBuilder;
import io.github.benas.randombeans.api.EnhancedRandom;
import io.github.benas.randombeans.api.Randomizer;
import io.github.benas.randombeans.randomizers.range.LocalDateRangeRandomizer;

import javax.validation.constraints.Past;
import java.time.LocalDate;

public class Foo {

    @Past
    private LocalDate birthDate;

    public static void main(String[] args) {
        EnhancedRandom enhancedRandom = new EnhancedRandomBuilder()
                .randomize(FieldDefinitionBuilder.field().named("birthDate").ofType(LocalDate.class).inClass(Foo.class).get(), new Randomizer<LocalDate>() {
                    LocalDateRangeRandomizer localDateRangeRandomizer = new LocalDateRangeRandomizer(LocalDate.now().minusYears(10), LocalDate.now());
                    @Override
                    public LocalDate getRandomValue() {
                        return localDateRangeRandomizer.getRandomValue();
                    }
                })
                .build();

        Foo foo = enhancedRandom.nextObject(Foo.class);
        System.out.println(foo.birthDate);
    }
}
```

**Comment by PascalSchumacher** [comment]
@benas See https://github.com/benas/random-beans/pull/331 for what I wanted to say about using `TimeRandomizerRegistry`.

**Comment by benas** [comment]
@PascalSchumacher Thanks! Sorry for misunderstanding, I thought you mean using `TimeRandomizerRegistry` in client code (with`EnhancedRandomBuilder#registerRandomizerRegistry`) not in RB code.

**Comment by benas** [comment]
@neetkee A fix for this issue has been deployed in version `3.9.0-SNAPSHOT`. Now it is possible to use Bean Validation annotations with the Date/Time API types. I'm closing this issue as resolved, but you can give the fix a try (See [here](https://github.com/benas/random-beans/wiki/Getting-Started#maven-usage) for how to import the snapshot version) and re-open the ticket if necessary.

Many thanks to @PascalSchumacher for the fix!
