### ISSUE TITLE
Issue with regexp with both leading and tailing boundary (^ $) matchers

### ISSUE THREAD

**Issue by weronika-redlarska** [benas/random-beans#330]
When there are both ^ and $ boundary matchers in the regexp pattern, the tailing matcher $ is not removed. I have submitted a pull request that fixes this issue: #329

**Comment by benas** [comment]
Indeed, that's a bug in RB . Thank you @weronika-redlarska for reporting the issue and fixing it!

I'm closing this issue as it is fixed with #329.
