### ISSUE TITLE
Add support for `@NotEmpty` annotation from the  Bean Validation API

### ISSUE THREAD

**Issue by benas** [benas/random-beans#339]
As of v3.8, Random Beans does not support `@NotEmpty` annotation. This annotation has been added in Bean Validation v2.0 which is already the version supported by RB.

**Comment by PascalSchumacher** [comment]
But doesn't Random Beans already generate non-empty collections and strings by default?

**Comment by benas** [comment]
Yes, I was thinking about the use case where RB is configured to generate empty collections in the whole object graph except one or two that are annotated with `@NotEmpty`.

**Comment by benas** [comment]
What I meant is something like:

```java
import io.github.benas.randombeans.EnhancedRandomBuilder;
import io.github.benas.randombeans.api.EnhancedRandom;
import org.junit.jupiter.api.Test;

import javax.validation.constraints.NotEmpty;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class TestNotEmpty {

    @Test
    void nonEmptyFieldsShouldNotBeEmpty() {
        EnhancedRandom enhancedRandom = new EnhancedRandomBuilder()
                .stringLengthRange(0, 0)
                .collectionSizeRange(0, 0)
                .build();

        Foo foo = enhancedRandom.nextObject(Foo.class);

        assertThat(foo.firstName).isBlank();
        assertThat(foo.lastName).isNotBlank();
        assertThat(foo.nicknames).isEmpty();
        assertThat(foo.friends).isNotEmpty();
    }

    static class Foo {

        private String firstName;
        @NotEmpty
        private String lastName;
        private List<String> nicknames;
        @NotEmpty
        private List<String> friends;

        // getters and setters
    }
}
```

This fails with v3.8.0. FYI, I'm working on this for now.

**Comment by benas** [comment]
That was not as easy as I expected.. Initial work pushed to branch `issue-339`, but BV tests are failing. It looks like I hit type erasure when RB tries to randomize a generic collection or map. Even though `NotEmptyAnnotationHandler` uses a different `EnhancedRandom` instance where the defaults should make it generate non empty collections and maps, it still generates empty collections and maps (But that's not the case for strings and arrays which are correctly randomized as non empty).

When I debug one of the failing tests, I see that a randomizer is returned as expected from `NotEmptyAnnotationHandler` (result of the lambda), and when the current field is a collection or map, [isIntrospectable](https://github.com/benas/random-beans/blob/ca75385e034254bbe590f1ff11337d8abcfc8a02/random-beans/src/main/java/io/github/benas/randombeans/EnhancedRandomImpl.java#L99) is obviously false and we hit [collectionPopulator.getEmptyImplementationForCollectionInterface(type)](https://github.com/benas/random-beans/blob/ca75385e034254bbe590f1ff11337d8abcfc8a02/random-beans/src/main/java/io/github/benas/randombeans/EnhancedRandomImpl.java#L139). The end result is an empty collection/map which is of course not valid according to `@NotEmpty`..

@PascalSchumacher Any idea?

I tried the other path of something like:

* If type is String => return `StringRandomizer`
* If type is collection => get the genetic type from the field, generate random instances, etc
* If type is map => same as collection
* etc

But I would not go this path.

NB: No objection on my side to declare this as limitation in the known limitation section.

**Comment by PascalSchumacher** [comment]
Yes, if the field is a collection `getType` just returns the raw type. The actual type can be accessed with in `field.getType().getGenericType`. We would need access to (part of the logic) in `FieldPopulator` to generate a collection/map filled with the correct objects. But if if `FieldPopulator` was accessible we would also need a `RandomizationContext` to invoke `#generateRandomValue`. So I guess we have to live with this limitation.

**Comment by benas** [comment]
> The actual type can be accessed with in `field.getType().getGenericType`. We would need access to `FieldPopulator` to generate a collection/map filled with the correct objects.

Indeed, that's what I tried in the "other path", hoping to reuse `MapPopulator` and `CollectionPopulator`..

> So I guess we have to live with this limitation.

ok we are on the same page. I will merge the changes and update the docs with this limitation.

Thank you for your time and for your quick feedback!

**Comment by PascalSchumacher** [comment]
Upon further think about this, I believe we should revert this change, because it causes random beans to generate an invalid object for every generic `Collection` and `Map` annotated with `@NotEmpty`.

This test passes (bean is valid) with Random Beans `3.8.0`:

```java
static class Bean {
    @NotEmpty
    public List<String> strings;
    @NotEmpty
    public Map<Integer, String> map;
}

@Test
void test() {
    EnhancedRandom enhancedRandom = aNewEnhancedRandom();
    assertThat(enhancedRandom.nextObject(Bean.class).strings).isNotEmpty();
    assertThat(enhancedRandom.nextObject(Bean.class).map).isNotEmpty();
}
```

but it fails with current master.

**Comment by benas** [comment]
I thought we agreed to live with that limitation and update the docs accordingly (which I did [here](https://github.com/benas/random-beans/wiki/known-limitations#bean-validation)).

The test passes with 3.8 because by default RB generates non empty collections and maps (so basically the annotation is useless).

I think the only use case (but probably I'm missing another one) of `@NotEmpty` is for someone who wants all collections/maps in the object graph to be empty except those annotated to be not empty (example given [here](https://github.com/benas/random-beans/issues/339#issuecomment-462167159) which fails with 3.8). 

Does this make sense?

**Comment by PascalSchumacher** [comment]
As said above I did not consider that this feature will change the behavior of Random Beans to generate invalid beans, if a bean has a field which is a collection or map annotated with `@NotEmpty`.

For example I use bean validation to validate JSON objects after they have been serialized to objects. Every `List` field that is non-optional is annotated with `@NotEmpty`. Random Beans 3.8.0 will generate valid objects. Current master will not generate valid objects.

**Comment by benas** [comment]
Well that indeed can look like a breaking change, but again, the fact that v3.8 generates valid data for types having `NotEmpty` is accidental. If I force `.stringLengthRange(0, 0)` and `.collectionSizeRange(0, 0)` to have empty collections/maps everywhere except a particular collection, it still not possible with v3.8.

In hindsight, I agree with you. I believe that not introducing a breaking change and updating the docs to mention that `@NotEmpty` is not supported is better than adding (partial) support for it and eventually break some existing users code.

I will revert the change and declare `@NotEmpty` as not supported. Thanks.

**Comment by benas** [comment]
> I will revert the change

Done in 0fe66af17989569f7fad533c79f5a0a3e5884d60.

I will omit mentioning that `NotEmpty` is not supported because it is implicitly supported by default. So I will keep that implicit in the docs too 🙃

**Comment by PascalSchumacher** [comment]
Thanks! 👍
