### ISSUE TITLE
Populator is trying to set private static final long serialVersionUID and fails

### ISSUE THREAD

**Issue by wheredevel** [benas/random-beans#56]
My questions are:
- Any way to prevent this?
- Why setting constants in the first place?
- Tried exclusion: how to deal with fields of fields of fields i want to exclude?
- Tried @Exclude annotation: how to deal with classes that are coming from external jars?

....
Caused by: java.lang.IllegalAccessException: Can not set static final long field java.time.ZonedDateTime.serialVersionUID to java.lang.Long
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at sun.reflect.UnsafeQualifiedStaticLongFieldAccessorImpl.set(UnsafeQualifiedStaticLongFieldAccessorImpl.java:77)
	at java.lang.reflect.Field.set(Field.java:764)
	at io.github.benas.randombeans.util.ReflectionUtils.setProperty(ReflectionUtils.java:79)
	at io.github.benas.randombeans.PopulatorImpl.populateField(PopulatorImpl.java:143)
	at io.github.benas.randombeans.PopulatorImpl.doPopulateBean(PopulatorImpl.java:104)
	... 44 more

**Comment by benas** [comment]
Hi,

Thank you for pointing out this issue!

> Populator is trying to set private static final long serialVersionUID and fails. Any way to prevent this?

This is a regression of issue #1 . I just fixed that, it should be fine now.

> Why setting constants in the first place?

Constants are not modified. If the class designer has designed the field to be constant, Random Beans does not touch it.

> Tried exclusion: how to deal with fields of fields of fields i want to exclude?

You can use the dotted notation for that. See example [here](https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/PopulatorImplTest.java#L96). This has been introduced in issue #24 .

> Tried @Exclude annotation: how to deal with classes that are coming from external jars?

Random Beans provides two ways to exclude fields:
- Either declaratively through the `@Exclude` annotation
- Or programatically through the API

See the [wiki](https://github.com/benas/random-beans/wiki/excluding-fields) page for details. Using the annotation is of course intrusive and is an option only for classes you can modify (see my comment [here](https://github.com/benas/random-beans/issues/20#issue-55960207)). For other classes, you can exclude fields programatically.

Kind regards
Mahmoud

**Comment by wheredevel** [comment]
Thanks for the quick response.
As you pointed:
> Tried exclusion: how to deal with fields of fields of fields i want to exclude?
>> You can use the dotted notation for that. See example here. This has been introduced in issue #24 .

I tried that. And it did not work. I could try to debug. but I lack a few examples.
As I said: fields of fields of fields?...
And also how to deal with fields residing in object that are inside a collection i'm trying to populate?

**Comment by benas** [comment]
> I tried that. And it did not work.

Can you give an example please? This will help to figure out what's going on..

> how to deal with fields residing in object that are inside a collection, that i'm trying to populate?

Not sure I understand this point, do you mean fields that are of collection type?

**Comment by wheredevel** [comment]
Here're the settings.

class A{
  String s1
  String s2
}

class B {
  A a1
  A a2
}

class C {
  B b1
  B b2
  List<B> b3
}

>> I tried that. And it did not work.
> Can you give an example please? This will help to figure out what's going on..

populator.populateBean(C.class, "b2") // please, confirm that it works
populator.populateBean(C.class, "b2.a2") // please, confirm that it works
populator.populateBean(C.class, "b2.a2.s2") // please, confirm that it works

>> how to deal with fields residing in object that are inside a collection, that i'm trying to populate?
> Not sure I understand this point, do you mean fields that are of collection type?

populator.populateBean(C.class, "b3") // please, confirm that it works
populator.populateBean(C.class, "b3.a2") // please, confirm that it works
populator.populateBean(C.class, "b3.a2.s2") // please, confirm that it works

And, one more thing:

It might be nice to have a NoRandomizer = another way to Exclude...
Like that:

		return PopulatorBuilder.aNewPopulatorBuilder()
			.registerRandomizer(Serializable.class,
				Long.class,
				"serialVersionUID",
				new NoRandomizer())
			.build();

**Comment by benas** [comment]
Hi Pavel,

I created two separate issues to discuss about:

- The problem with excluding fields using the dotted notation ( issue #60 )
- The new suggested way of excluding fields (issue #61 )

Let's continue the discussion there.

In regards to this issue, as I said , the population of static final fields should not happen and this is a regression. I have fixed it. It would be great if you give it a try and confirm so that I close the issue.

Regards
Mahmoud

**Comment by wheredevel** [comment]
How can I try the fixed version?
I pull from Maven repo... 2.0.0-SNAPSHOT

**Comment by benas** [comment]
You need to declare the snapshot repository and add the dependency to the snapshot version:

https://github.com/benas/random-beans#current-version

**Comment by wheredevel** [comment]
I cloned from git.
Seems to be working.
All "green" ;)

**Comment by benas** [comment]
Great, thank you for taking time to test!
