### ISSUE TITLE
Unable to exclude field using the dotted notation

### ISSUE THREAD

**Issue by benas** [benas/random-beans#60]
This issue has been reported by @wheredevel in #56 

Here is the setup to reproduce the issue:

```
class A{
String s1
String s2
}

class B {
A a1
A a2
}

class C {
B b1
B b2
List b3
}
```

@wheredevel I was able to reproduce the issue with your example, and fixed it.

> populator.populateBean(C.class, "b2") // please, confirm that it works

Yes, it should work now, [here](https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/FieldExclusionTest.java#L85) is the passing test for that

> populator.populateBean(C.class, "b2.a2") // please, confirm that it works

Yes, it should work now, [here](https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/FieldExclusionTest.java#L104) is the passing test for that

> populator.populateBean(C.class, "b2.a2.s2") // please, confirm that it works

Yes, it should work now, [here](https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/FieldExclusionTest.java#L127) is the passing test for that

> populator.populateBean(C.class, "b3") // please, confirm that it works

Yes, it should work now, [here](https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/FieldExclusionTest.java#L149) is the passing test for that

> populator.populateBean(C.class, "b3.a2") // please, confirm that it works
> populator.populateBean(C.class, "b3.a2.s2") // please, confirm that it works

These two last cases do not make sense, what does it mean to exclude `field a2 in List<B> b3` ?
So this kind of exclusion is [ignored](https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/FieldExclusionTest.java#L177).

I have merged the fix in the master branch and published the last snapshot version `2.0.0-SNAPSHOT` to maven central.

Please give it a try and tell me if you have any issue.
Kind regards
Mahmoud

**Comment by wheredevel** [comment]
@benas ,

>>populator.populateBean(C.class, "b3.a2") // please, confirm that it works
>These two last cases do not make sense, what does it mean to exclude field a2 in List<B> b3 ?
>So this kind of exclusion is ignored.

They do make sense:
**"Exclude field a2 in every object of type B in the List<B>, named b3."**
That's what I meant.

**Comment by benas** [comment]
> "Exclude field a2 in every object of type B in the List, named b3 of objects of type C."

I see your point, but what if b3 was of type `Map<Person, B>` instead of `List<B>` ? What would exclude `b3.a2` mean, exclude a2 from keys of type `Person` or from values of type B? I'm not sure this notation allows you to express what you are looking for. This is out of scope and I think simple (ie non collection) field exclusion using the dotted notation is fair enough.

**Comment by wheredevel** [comment]
You're probably right. 
I gotta use more and more of the Populator to have more ideas.
Great job, @benas, by the way!
