### ISSUE TITLE
Exclude fields with a NoRandomizer

### ISSUE THREAD

**Issue by benas** [benas/random-beans#61]
This feature has been requested by @wheredevel in issue #56 :

It might be nice to have a NoRandomizer = another way to Exclude...
Like that:

```
return PopulatorBuilder.aNewPopulatorBuilder()
        .registerRandomizer(Serializable.class,
            Long.class,
            "serialVersionUID",
            new NoRandomizer())
        .build();
```

**Comment by benas** [comment]
There is already a `NullRandomizer` that you can use to exclude fields this way. This is a typical implementation of the Null Object Pattern.

Would this be what you are looking for?

**Comment by wheredevel** [comment]
In my case it was an attempt to do Exclude.
So, I guess, the NoRandomizer a different case than NullRandomizer: it's whenever you don't want to randomize a filed or type at all. Exclusion, as I said - yet another way.

**Comment by benas** [comment]
I see, kind of a `SkipRandomizer`. This is easy to implement, we just need to make Random Beans check if the registered randomizer for the current field is of type `NoRandomizer` and simply skip/ignore the field.

But what if we simply add a method to the API to exclude fields like:

```java
Populator p = aNewPopulator()
   .exclude(Person.class, String.class, "name")
   .build();

Person person = p.populateBean(Person.class);
```
This is more natural and equivalent to registering a `NoRandomizer` for the field `name` but without the need for such a randomizer. This makes it possible to exclude fields programmatically. What do you think?

**Comment by wheredevel** [comment]
I'd offer both. Like, "choose your flavor"...
Ah, and, BTW, I believe you already have an annotation option too, right?

I myself don't mind contributing by codding. 
I already cloned the repo. Watched the code. Very-very nicely written. 

Do you have contributing instructions somewhere?

**Comment by benas** [comment]
> I'd offer both. Like, "choose your flavor"...
> Ah, and, BTW, I believe you already have an annotation option too, right?

Indeed, there are already [2 ways to exclude fields](https://github.com/benas/random-beans/wiki/excluding-fields), and will add the third way with this suggested feature. So we can say the user can already choose his flavor right away :smile: 

> I already cloned the repo. Watched the code. Very-very nicely written.

Thank you!

> Do you have contributing instructions somewhere?

Not really, you are welcome to open pull requests and contribute to the project.

**Comment by benas** [comment]
Hi Pavel,

I've added the third way to exclude fields as you suggested, here is an example:

```java
// given
populator = aNewPopulatorBuilder()
   .exclude(field().named("name").ofType(String.class).inClass(Person.class).get())
   .build();

 // when
Person person = populator.populateBean(Person.class);

// then
assertThat(person).isNotNull();
assertThat(person.getName()).isNull();
```

It's already merged in the master branch.
It uses a `SkipRandomizer` behind the scene ;-)
I've also added a small builder to exclude fields with a more readable fluent API.

Looking forward to hear your thoughts.
Kind regards
Mahmoud

**Comment by wheredevel** [comment]
Thanks, I'll give it a try.

**Comment by benas** [comment]
Hi, great! Looking forward for your feedback.

You can also exclude  fields using the `SkipRandomizer` explicitely:

```java
populator = aNewPopulatorBuilder()
   .randomize(field().named("name").ofType(String.class).inClass(Person.class).get(), new SkipRandomizer())
   .build();
```

Personally, I prefer the `exclude` method.. but that's a matter of taste :smile: 

Kind regards
Mahmoud
