### ISSUE TITLE
Should collections without generics be generated empty?

### ISSUE THREAD

**Issue by PascalSchumacher** [benas/random-beans#66]
At the moment collections without generic types are filled `String`s. I wonder if it would be more generally useful if they were just empty?

**Comment by benas** [comment]
> At the moment collections without generic types are filled Strings.

Yes, this has been added in [this PR](https://github.com/benas/random-beans/pull/38/files#diff-ded1e47d146cf5f4d680ed6e256f966bR313). The choice of String as a base class for objects in raw collections has been made because some collections require Comparable objects (see comment of the author of the PR)

> I wonder if it would be more generally useful if they were just empty?

As of version 1.x, Random Beans generates empty collections. Generating non-empty collections has been [requested](https://github.com/benas/random-beans/issues/19) and planned for release 2.x. What makes you think that it would be more useful is they were just empty?

**Comment by PascalSchumacher** [comment]
I agree that generating non-empty collections is useful :+1: , but only if the collection contains elements of the right type.

Putting strings into collections without generics is guesswork. It's just a gut feeling, but I fear that this will be the wrong a lot.

BTW: Random Beans 2.0 can not generate Collections with generic place holders: e.g. `List<?>`, `List<? extends Runnable>` etc. fail, because Random Beans tries to create beans for `?`, `? extends Runnable` etc. Maybe in these cases an empty collection should be generated instead?

**Comment by benas** [comment]
Hello Pascal,

You are right and I think that we think the same way :smile: See my comment on the subject here: https://github.com/benas/random-beans/issues/19#issuecomment-71988275 : 

> if the field is a non-typed collection (private Set accounts), then jPopulator cannot know which type of objects to generate. Hence, it will generate an empty collection (as it does now).

When I got the PR, I said "hmm why not.." and then it was merged, but may be too quickly. As you said, Random Beans should not make assumptions or guess what type it should fill in the collection, so if there are people in 2016 still using raw collections, then they should accept empty collections or use a custom randomizer for the field.

That said, I'll revert back the code to generate empty collections for raw collections..

Thank you for pointing this out just before the release!

Best regards
Mahmoud

**Comment by PascalSchumacher** [comment]
:smile:

**Comment by benas** [comment]
That's done. Raw collection are generated empty now. The code is even simpler!

> BTW: Random Beans 2.0 can not generate Collections with generic place holders: e.g. List<?>, List<? extends Runnable> etc. fail, because Random Beans tries to create beans for ?, ? extends Runnable etc. Maybe in these cases an empty collection should be generated instead?

I'll add a test case for that asap.

**Comment by benas** [comment]
The last test case I'm working on before the release is the following:

```java
public class CompositeCollectionBean {

    private List<List<String>> listOfLists;
    private Map<Person, List<String>> personToNicknames;

}
```

Currently it fails.. it should generate an empty collection when the field is a composite collection type. I think supporting simple collection type is fair enough..

**Comment by PascalSchumacher** [comment]
I guess it's not that hard to support this, but I agree support for this can be postponed to a later version.
