### ISSUE TITLE
Add an example pom.xml / build.gradle dependency entry

### ISSUE THREAD

**Issue by dead10ck** [benas/random-beans#69]
An example entry for a `pom.xml` or `build.gradle` in the documentation would be helpful. Currently, I can't even tell where this lib is hosted. It doesn't appear to be on maven central, and the only place in the docs that mentions a repository to download from is for the latest snapshot version.

**Comment by PascalSchumacher** [comment]
Hi dead10ck, 

this project used to be called jPopulator, you can get the stable version from maven central: http://search.maven.org/#artifactdetails|io.github.benas|jpopulator|1.2.0|jar

**Comment by dead10ck** [comment]
Wait, so does 2.0.0 have a stable release right now?

**Comment by PascalSchumacher** [comment]
There's no stable 2.0.0 release yet.

**Comment by benas** [comment]
Hi @dead10ck ,

You can find information about current version in the home page of the project:

https://github.com/benas/random-beans#current-version

The current stable version is 1.2.0 and is deployed on maven central, just clic on the badge in the home page to get the coordinates. The project was called jPopulator and it has been renamed to Random Beans.

There is also a getting started page on the wiki:

https://github.com/benas/random-beans/wiki/Getting-Started

Version 2.0.0 will be released shortly, I made the mistake to update the documentation before the release. This is a new concept, Documentation Driven Development, just like TDD, you see? no, I'm just kidding :smile: I shouldn't have done this..

@PascalSchumacher Thank you Pascal for your reply.

**Comment by dead10ck** [comment]
@benas ahh, I see. Thank you both for your quick replies!
