### ISSUE TITLE
After the API refactoring - broken interface.

### ISSUE THREAD

**Issue by wheredevel** [benas/random-beans#77]
In the current 2.0.0-SNAPSHOT the following code is broken:
`Populator populator = new PopulatorBuilder().build();
Person person = populator.populateBean(Person.class);`

Reason: Populator class is missing from ...api package.

Now, I saw a comment on API refactoring. 
Where is the bug: in the documentation OR in the interface.

**Comment by benas** [comment]
I've updated the documentation, see the snippet here:

https://github.com/benas/random-beans#why-random-beans

I'm currently preparing the release and will update the wiki accordingly.

**Comment by wheredevel** [comment]
Thanks man.
I understand the rationale for the API change. ( FYI, I liked "Populator" better...;o) )
Still, such a change on a SNAPSHOT without advancing a version or at least tagging/branching - is not a very good idea...

**Comment by benas** [comment]
> Still, such a change on a SNAPSHOT without advancing a version or at least tagging/branching - is not a very good idea...

I have advanced the major version number. The current production version is 1.2.0, the next version is a major release 2.0.0 since it includes API breaking changes. What's wrong with that? It is the standard [semver](http://semver.org/) schema.

**Comment by wheredevel** [comment]
I mean, for those of us who were using the 2.0.0-SNAPSHOT and the Populator suddenly disappeared...
In such case, I would advance the snapshot to be 2.0.1-SNAPSHOT, before the API change.

**Comment by benas** [comment]
I see, but in this case It will be confusing for users to use the snapshot version 2.18.0-SNAPSHOT (after several API changes) and then move back to the 2.0.0-RELEASE when the library is released, since I would like to move from the current 1.2.0 to 2.0.0 .. Do you agree? But may be there is a better way to do it :smile: 

When I use a snapshot version of a library, I usually expect API changes without any problem

**Comment by benas** [comment]
May be I should have made this API deprecated in v2 and then remove in v3 ..

**Comment by benas** [comment]
Hi Pavel,

I have released version 2.0.0 and updated the documentation accordingly.

> Now, I saw a comment on API refactoring. 
Where is the bug: in the documentation OR in the interface.

Next time, I'll not make the same [mistake](https://github.com/benas/random-beans/issues/69#issuecomment-181716644) again :smile: 

In regards to the snapshot version, I could have used different snapshot versions for the same release, ie: 2.0.0-alpha, 2.0.0-beta, 2.0.0-RC1, etc 
This would let you know when there is an API change without making APIs "disappear" suddenly ..
You were right and I'm sorry for that.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi,

I just want to add an interesting link about this discussion:

http://stackoverflow.com/a/5901460

Hope this may help if someone come back to this thread later :smile:
