### ISSUE TITLE
FieldDefinitionBuilder is missing in wiki example

### ISSUE THREAD

**Issue by wheredevel** [benas/random-beans#81]
`EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
   .randomize(field().named("name").ofType(String.class).inClass(Person.class).get(), new NameRandomizer());
   .build();`

Should be:

`EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
   .randomize(**FieldDefinitionBuilder.**field().named("name").ofType(String.class).inClass(Person.class).get(), new NameRandomizer());
   .build();`

**Comment by benas** [comment]
Hi,

You are right, Explicit is better than implicit! I have updated the wiki with the explicit call to the static method `field()` in the `FieldDefinitionBuilder` API.

Thanks for pointing this out.

Regards
Mahmoud
