### ISSUE TITLE
Still can not easily register Class randomizer programatically

### ISSUE THREAD

**Issue by wheredevel** [benas/random-beans#82]
Hi,

I'm still struggling with registering Randomizer for a certain Type programatically.
Wiki describes randomizer registration for: field... named..of class.
While I need: just class.

Please, help. Did I miss the right line in a manual?

**Comment by benas** [comment]
Hi,

The short answer is : You can provide a [custom registry](https://github.com/benas/random-beans/wiki/Grouping-Randomizers) in which you associate a randomizer to a type.

Now this is a design question: As a user of the library, I want to be able to register a custom randomizer if the field:

* has a given type
* has a given name
* is declared in a given class
* is annotated with a given annotation
* (two, three or) All of the above

From an API design point of view, there should be a way to define how to identify a field in the process of bean introspection and this is the role of the `FieldDefinition` class.

Field name, type and declaring class is the common denominator to identify a field. You can not have two fields with the same name, same type and same declaring class. Field definition are [unique](https://github.com/benas/random-beans/blob/master/random-beans/src/main/java/io/github/benas/randombeans/FieldDefinition.java#L68) according to these three criteria. **For the moment**, `FieldDefinition` and its builder are designed to cover these criteria.

You can still use registries to provide custom randomizers by `Field` or by `Type`. When you implement a custom `RandomizerRegistry`, you get access to the `Field` being introspected and here you can get all informations above: field name, type, annotations etc and hence provide your custom field -> randomizer mapping.

Hope this helps
Kind regards
Mahmoud

**Comment by wheredevel** [comment]
Everything sounds right.
I'd only emphasize the existence of 2 API use-cases:
1. Building a specific randomizer - while specifying what registries to use, etc.
2. Invoking (a previously built) randomizer on a Class<?> - while modifying the randomization behavior during this particular randomization invocation only.

Case 1 is well covered.

Case 2 - there we can modify using FieldDefinition, which covers most cases.
Still, I had this edge case, when ALL the fields of a particular Type would have to be generated differently from Randomizer default. And FieldDefinition couldn't do the job for me. I wonder if there're should be a way - or is it just too much (for example, because the modification logic becomes too complex.)

**Comment by PascalSchumacher** [comment]
Possible fix: https://github.com/benas/random-beans/pull/97

**Comment by benas** [comment]
Hi @wheredevel 

@PascalSchumacher has kindly added support for registering a randomizer for a given type. This removes the need to implement a custom registry for that.

Would you please give it a try and see if everything is ok for you? I've just published an updated version of the 3.0.0-SNAPSHOT.

In the same way, do you think random beans would also add support to register a randomizer by field name in addition to field type? For example, this can be used like: For every field named "name", use the `NameRandomizer`. Does this make sense?

**Comment by benas** [comment]
Hi Pavel,

Your feature request will be released in v3.0.0 soon.

If you have any problem, don't hesitate to file a bug.

Kind regards
Mahmoud
