### ISSUE TITLE
Length from persistance api can be taken into account

### ISSUE THREAD

**Issue by heydenb** [benas/random-beans#83]
While storing the Object, I get:
ERROR: value too long for type character varying(20)

Probably because the String generator creates random strings longer than 20.

However the persistence API is used.
@Column(name="MY_COL", length=20)
private String col;

So, this could be taken into account by the framework I guess

**Comment by benas** [comment]
Hi,

I see. Have you tried to use a [Bean Validation](https://github.com/benas/random-beans/wiki/bean-validation-support) annotation? This allows you to generate random *valid* data. Here is an example:

```java
@javax.validation.constraints.Size(max = 20)
@Column(name="MY_COL", length=20)
private String col;
```

Random Beans will then generate random strings of length <= 20 characters. Note that to use this feature, you need to add the `random-beans-validation` module to your dependencies.

Another option is to register a `StringLengthRandomizer` programmatically:

```java
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
               .randomize(FieldDefinitionBuilder.field().named("col").ofType(String.class).inClass(yourObjectType.class).get(), new StringLengthRandomizer(0, 20))
                .build();
```

Hope this helps.
Kind regards

**Comment by heydenb** [comment]
Thanks. That helps a lot. I am going for the StringLengthRandomizer because in our case I don't want to touch the model directly if I can avoid it.

**Comment by benas** [comment]
Hi,

Glad that helped.

Annotations are intrusive indeed :rage: That's why Random Beans tries to provide two ways (both  declarative via annotations and programmatic through the API) for most features: field exclusion, randomizer registration, etc

Kind regards
Mahmoud

**Comment by Calabor-Hoc** [comment]
Usually there are numerous tables and corresponding domain boject. Specify a custom Randomizer for each of those columns can be strenuous. I think it would be a great feature if random bean can be configured to connect to the target database and introspect table structure than do the right randomization for us!
