### ISSUE TITLE
"Pre-initialized" Bean Fields are nulled

### ISSUE THREAD

**Issue by gpaul-idexx** [benas/random-beans#84]
When writing a dto, I often initialize collections to ensure they are never null. It appears that objenesis's approach to instantiation ends up producing an instance will null fields.Here's some code to show it. The first assert will pass, and the second will fail. Perhaps there is a perspective where this is desired behavior, but it was surprising to me, and not what I would prefer so I thought I would share.

`public class Main {
    public static void main(String[] args) {
        EnhancedRandomBuilder builder = new EnhancedRandomBuilder();
        builder.exclude(new FieldDefinition<>("myList", List.class, MyBean.class));

        assert new MyBean().getMyList().size() == 0;
        assert builder.build().nextObject(MyBean.class).getMyList().size() == 0;
    }

    public static class MyBean {
        private List<String> myList = new ArrayList<>();

        public List<String> getMyList() {
            return myList;
        }

        public void setMyList(List<String> myList) {
            this.myList = myList;
        }
    }
}
`

**Comment by benas** [comment]
Hi,

Thank you for pointing this out! This is a bug. Inline initialization of an excluded field should be used as is. Here is a failing test with version 2.0.0:

```java
import static io.github.benas.randombeans.FieldDefinitionBuilder.field;
import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import org.junit.Before;
import org.junit.Test;

import io.github.benas.randombeans.EnhancedRandomBuilder;
import io.github.benas.randombeans.api.EnhancedRandom;

public class TestExclusion {

    private EnhancedRandom enhancedRandom;

    @Before
    public void setUp() {
        enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
                .exclude(field().named("myList").ofType(List.class).inClass(MyBean.class).get())
                .build();
    }

    @Test
    public void whenFieldIsExcluded_thenItsInlineInitializationShouldBeUsedAsIs() {
        MyBean myBean = enhancedRandom.nextObject(MyBean.class);

        assertThat(myBean).isNotNull();
        assertThat(myBean.getMyList()).isNotNull().isEmpty();
    }

}
```

I'll fix it asap and keep you informed.

Kind regards
Mahmoud
