### ISSUE TITLE
random-beans-randomizers: Exception if java-faker does not support default locale

### ISSUE THREAD

**Issue by PascalSchumacher** [benas/random-beans#86]
For example I get:

>com.github.javafaker.service.LocaleDoesNotExistException: de_DE could not be found, does not have a corresponding yaml file
	at com.github.javafaker.service.FakeValuesService.<init>(FakeValuesService.java:22)
	at com.github.javafaker.Faker.<init>(Faker.java:46)
	at io.github.benas.randombeans.randomizers.FakerBasedRandomizer.<init>(FakerBasedRandomizer.java:52)

I think it would be nice if random-beans would use the english locale in this case.

**Comment by benas** [comment]
Indeed. Thank you for pointing this out!

The more general question is: what do you do when one of your dependencies has a bug?

You see now why I [try to minimize dependencies](https://github.com/benas/random-beans/pull/89#issuecomment-203927705) ..
and at the same time I don't want to reinvent the wheel by reusing 3rd party libraries (see commit message [here](https://github.com/benas/random-beans/commit/d1e40e2a6747aabac1836f9beb0dd6b99325aa7a))

This trade-off is never easy and requires a good analysis upfront to make a pragmatic decision.

Anyway, I'll try to fix that asap.

**Comment by PascalSchumacher** [comment]
>what do you do when one of your dependencies has a bug?

My take: Work around it the best you can.

I'm not sure this is a bug. If you use java-faker directly by default you get english data:

`String name  = new Faker().name();`

If you want data for your locale you have to pass in the locale e.g.:

`String name  = new Faker(Locale.FRENCH).name();`

 with random-beans your only option is to change the default locale e.g. by setting a system property.
