### ISSUE TITLE
Merge random-beans-java8 into random-beans?

### ISSUE THREAD

**Issue by PascalSchumacher** [benas/random-beans#88]
Should random-beans-java8 be merged into random-beans now that random-beans requires Java 8?

**Comment by benas** [comment]
Yes, this module made sense when the library was supposed to be Java 7 compatible (see issue and comment of #49 ).

Now that [prerequisites](https://github.com/benas/random-beans/wiki/Getting-Started#prerequisite) are clear for each version, Java 8 types support can be merged in the core module.

I'll plan the merge for next release.
